INDIAN_STATES = [
	("AN","Andaman and Nicobar Islands"),
	("Ap","Andhra Pradesh"),
	("AR","Arunachal Pradesh"),
	("AS","Assam"),
	("BR","Bihar"),
	("CG","Chhattisgarh"),
	("CH","Chandigarh"),
	("DD","Daman and Diu"),
	("DL","Delhi"),
	("GA","Goa"),
	("GJ","Gujarat"),
	("HR","Haryana"),
	("HP","Himachal Pradesh"),
	("JH","Jharkhand"),
	("JK","Jammu and Kashmir"),
	("KA","Karnataka"),
	("KL","Kerala"),
	("LA","Ladakh"),
	("LD","Lakshadweep"),
	("MP","Madhya Pradesh"),
	("MH","Maharashtra"),
	("MN","Manipur"),
	("ML","Meghalaya"),
	("MZ","Mizoram"),
	("NL","Nagaland"),
	("OD","Odisha"),
	("PY","Puducherry"),
	("RJ","Rajasthan"),
	("SK","Sikkim"),
	("TN","Tamil Nadu"),
	("TS","Telangana"),
	("TR","Tripura"),
	("UP","Uttar Pradesh"),
	("UK","Uttarakhand"),
	("WB","West Bengal"),
]
		