# -*- encoding: utf-8 -*-
pac_list = ["gcc",
            "gcc-8",
            "gcc-8-base",
            "libgcc1:amd64",
            "linux-compiler-gcc-8-x86",
            "libgcc1",
            "docker.io",
            "git",
            "python3-pip",
            "python3-devpi-common",
            "clang",
            "cmake",
            "make",
            "golang",
            "aria2",
            "net-tools",
            "htop",
            "tree",
            "sshfs",
            "python3-pyqt5*",
            "vim",
            "zlib1g-dev",
            "python3-devpi-common",
            "python3-py",
            "wine64"]
