# Generated by Django 5.1.6 on 2025-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odoosetup',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
