# Generated by Django 4.2.1 on 2023-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timor_locations", "0004_alter_administrativepost_date_modified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopoJson",
            fields=[
                ("id", models.SlugField(max_length=2048, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=2048, null=True)),
                ("quantization", models.DecimalField(decimal_places=8, max_digits=16)),
                ("simplification", models.DecimalField(decimal_places=8, max_digits=16)),
                ("topojson", models.JSONField()),
            ],
        ),
    ]
