class IncompatibleImplementation(TypeError):
    def __init__(self, abstract: type, concrete: type) -> None: ...

class InterfaceNotRegistered(KeyError):
    def __init__(self, abstract: type) -> None: ...

class ImplementationNotFound(KeyError):
    def __init__(self, concrete_name: str) -> None: ...
