depends = ('ITKPyBase', 'MinimalPathExtraction', 'ITKTransform', 'ITKThresholding', 'ITKTestKernel', 'ITKTestKernel', 'ITKStatistics', 'ITKSpatialObjects', 'ITKSmoothing', 'ITKRegistrationCommon', 'ITKRegionGrowing', 'ITKPDEDeformableRegistration', 'ITKOptimizers', 'ITKLabelVoting', 'ITKImageSources', 'ITKImageIntensity', 'ITKImageGradient', 'ITKImageFunction', 'ITKImageFilterBase', 'ITKImageFeature', 'ITKIOTransformBase', 'ITKIOSpatialObjects', 'ITKIOMeta', 'ITKIOImageBase', 'ITKFFT', 'ITKDistanceMap', 'ITKCommon', 'ITKBinaryMathematicalMorphology', 'ITKAnisotropicSmoothing', )
templates = (  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsISS2', False, 'itk::Image<signed short, 2>'),
  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsIUC2', False, 'itk::Image<unsigned char, 2>'),
  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsIUS2', False, 'itk::Image<unsigned short, 2>'),
  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsISS3', False, 'itk::Image<signed short, 3>'),
  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsIUC3', False, 'itk::Image<unsigned char, 3>'),
  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsIUS3', False, 'itk::Image<unsigned short, 3>'),
  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsISS4', False, 'itk::Image<signed short, 4>'),
  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsIUC4', False, 'itk::Image<unsigned char, 4>'),
  ('ComputeBinaryImageSimilarityMetrics', 'tube::ComputeBinaryImageSimilarityMetrics', 'tubeComputeBinaryImageSimilarityMetricsIUS4', False, 'itk::Image<unsigned short, 4>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsISS2', False, 'itk::Image<signed short, 2>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIUC2', False, 'itk::Image<unsigned char, 2>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIUS2', False, 'itk::Image<unsigned short, 2>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIF2', False, 'itk::Image<float, 2>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsID2', False, 'itk::Image<double, 2>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsISS3', False, 'itk::Image<signed short, 3>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIUC3', False, 'itk::Image<unsigned char, 3>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIUS3', False, 'itk::Image<unsigned short, 3>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIF3', False, 'itk::Image<float, 3>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsID3', False, 'itk::Image<double, 3>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsISS4', False, 'itk::Image<signed short, 4>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIUC4', False, 'itk::Image<unsigned char, 4>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIUS4', False, 'itk::Image<unsigned short, 4>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsIF4', False, 'itk::Image<float, 4>'),
  ('ComputeImageSimilarityMetrics', 'tube::ComputeImageSimilarityMetrics', 'tubeComputeImageSimilarityMetricsID4', False, 'itk::Image<double, 4>'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsSS2', False, 'signed short, 2'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsUC2', False, 'unsigned char, 2'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsUS2', False, 'unsigned short, 2'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsF2', False, 'float, 2'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsD2', False, 'double, 2'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsSS3', False, 'signed short, 3'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsUC3', False, 'unsigned char, 3'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsUS3', False, 'unsigned short, 3'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsF3', False, 'float, 3'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsD3', False, 'double, 3'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsSS4', False, 'signed short, 4'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsUC4', False, 'unsigned char, 4'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsUS4', False, 'unsigned short, 4'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsF4', False, 'float, 4'),
  ('ComputeImageStatistics', 'tube::ComputeImageStatistics', 'tubeComputeImageStatisticsD4', False, 'double, 4'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSSS2', False, 'itk::Image<signed short,2>,itk::Image<signed short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSUC2', False, 'itk::Image<signed short,2>,itk::Image<unsigned char,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSUS2', False, 'itk::Image<signed short,2>,itk::Image<unsigned short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSF2', False, 'itk::Image<signed short,2>,itk::Image<float,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSD2', False, 'itk::Image<signed short,2>,itk::Image<double,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCSS2', False, 'itk::Image<unsigned char,2>,itk::Image<signed short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCUC2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned char,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCUS2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCF2', False, 'itk::Image<unsigned char,2>,itk::Image<float,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCD2', False, 'itk::Image<unsigned char,2>,itk::Image<double,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSSS2', False, 'itk::Image<unsigned short,2>,itk::Image<signed short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSUC2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned char,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSUS2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSF2', False, 'itk::Image<unsigned short,2>,itk::Image<float,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSD2', False, 'itk::Image<unsigned short,2>,itk::Image<double,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFSS2', False, 'itk::Image<float,2>,itk::Image<signed short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFUC2', False, 'itk::Image<float,2>,itk::Image<unsigned char,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFUS2', False, 'itk::Image<float,2>,itk::Image<unsigned short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFF2', False, 'itk::Image<float,2>,itk::Image<float,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFD2', False, 'itk::Image<float,2>,itk::Image<double,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDSS2', False, 'itk::Image<double,2>,itk::Image<signed short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDUC2', False, 'itk::Image<double,2>,itk::Image<unsigned char,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDUS2', False, 'itk::Image<double,2>,itk::Image<unsigned short,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDF2', False, 'itk::Image<double,2>,itk::Image<float,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDD2', False, 'itk::Image<double,2>,itk::Image<double,2>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSSS3', False, 'itk::Image<signed short,3>,itk::Image<signed short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSUC3', False, 'itk::Image<signed short,3>,itk::Image<unsigned char,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSUS3', False, 'itk::Image<signed short,3>,itk::Image<unsigned short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSF3', False, 'itk::Image<signed short,3>,itk::Image<float,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSD3', False, 'itk::Image<signed short,3>,itk::Image<double,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCSS3', False, 'itk::Image<unsigned char,3>,itk::Image<signed short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCUC3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned char,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCUS3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCF3', False, 'itk::Image<unsigned char,3>,itk::Image<float,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCD3', False, 'itk::Image<unsigned char,3>,itk::Image<double,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSSS3', False, 'itk::Image<unsigned short,3>,itk::Image<signed short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSUC3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned char,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSUS3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSF3', False, 'itk::Image<unsigned short,3>,itk::Image<float,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSD3', False, 'itk::Image<unsigned short,3>,itk::Image<double,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFSS3', False, 'itk::Image<float,3>,itk::Image<signed short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFUC3', False, 'itk::Image<float,3>,itk::Image<unsigned char,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFUS3', False, 'itk::Image<float,3>,itk::Image<unsigned short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFF3', False, 'itk::Image<float,3>,itk::Image<float,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFD3', False, 'itk::Image<float,3>,itk::Image<double,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDSS3', False, 'itk::Image<double,3>,itk::Image<signed short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDUC3', False, 'itk::Image<double,3>,itk::Image<unsigned char,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDUS3', False, 'itk::Image<double,3>,itk::Image<unsigned short,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDF3', False, 'itk::Image<double,3>,itk::Image<float,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDD3', False, 'itk::Image<double,3>,itk::Image<double,3>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSSS4', False, 'itk::Image<signed short,4>,itk::Image<signed short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSUC4', False, 'itk::Image<signed short,4>,itk::Image<unsigned char,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSUS4', False, 'itk::Image<signed short,4>,itk::Image<unsigned short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSF4', False, 'itk::Image<signed short,4>,itk::Image<float,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskSSD4', False, 'itk::Image<signed short,4>,itk::Image<double,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCSS4', False, 'itk::Image<unsigned char,4>,itk::Image<signed short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCUC4', False, 'itk::Image<unsigned char,4>,itk::Image<unsigned char,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCUS4', False, 'itk::Image<unsigned char,4>,itk::Image<unsigned short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCF4', False, 'itk::Image<unsigned char,4>,itk::Image<float,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUCD4', False, 'itk::Image<unsigned char,4>,itk::Image<double,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSSS4', False, 'itk::Image<unsigned short,4>,itk::Image<signed short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSUC4', False, 'itk::Image<unsigned short,4>,itk::Image<unsigned char,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSUS4', False, 'itk::Image<unsigned short,4>,itk::Image<unsigned short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSF4', False, 'itk::Image<unsigned short,4>,itk::Image<float,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskUSD4', False, 'itk::Image<unsigned short,4>,itk::Image<double,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFSS4', False, 'itk::Image<float,4>,itk::Image<signed short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFUC4', False, 'itk::Image<float,4>,itk::Image<unsigned char,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFUS4', False, 'itk::Image<float,4>,itk::Image<unsigned short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFF4', False, 'itk::Image<float,4>,itk::Image<float,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskFD4', False, 'itk::Image<float,4>,itk::Image<double,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDSS4', False, 'itk::Image<double,4>,itk::Image<signed short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDUC4', False, 'itk::Image<double,4>,itk::Image<unsigned char,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDUS4', False, 'itk::Image<double,4>,itk::Image<unsigned short,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDF4', False, 'itk::Image<double,4>,itk::Image<float,4>'),
  ('ComputeTrainingMask', 'tube::ComputeTrainingMask', 'tubeComputeTrainingMaskDD4', False, 'itk::Image<double,4>,itk::Image<double,4>'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageSS2', False, 'signed short, 2'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageSS3', False, 'signed short, 3'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageUC2', False, 'unsigned char, 2'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageUC3', False, 'unsigned char, 3'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageUS2', False, 'unsigned short, 2'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageUS3', False, 'unsigned short, 3'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageF2', False, 'float, 2'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageF3', False, 'float, 3'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageD2', False, 'double, 2'),
  ('ComputeTubeFlyThroughImage', 'tube::ComputeTubeFlyThroughImage', 'tubeComputeTubeFlyThroughImageD3', False, 'double, 3'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresSS2', False, 'signed short, 2'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresSS3', False, 'signed short, 3'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresUC2', False, 'unsigned char, 2'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresUC3', False, 'unsigned char, 3'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresUS2', False, 'unsigned short, 2'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresUS3', False, 'unsigned short, 3'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresF2', False, 'float, 2'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresF3', False, 'float, 3'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresD2', False, 'double, 2'),
  ('ComputeTubeMeasures', 'tube::ComputeTubeMeasures', 'tubeComputeTubeMeasuresD3', False, 'double, 3'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS2ISS2', False, 'itk::Image<signed short, 2>, itk::Image<signed short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS2IUC2', False, 'itk::Image<signed short, 2>, itk::Image<unsigned char, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS2IUS2', False, 'itk::Image<signed short, 2>, itk::Image<unsigned short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC2ISS2', False, 'itk::Image<unsigned char, 2>, itk::Image<signed short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC2IUC2', False, 'itk::Image<unsigned char, 2>, itk::Image<unsigned char, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC2IUS2', False, 'itk::Image<unsigned char, 2>, itk::Image<unsigned short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS2ISS2', False, 'itk::Image<unsigned short, 2>, itk::Image<signed short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS2IUC2', False, 'itk::Image<unsigned short, 2>, itk::Image<unsigned char, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS2IUS2', False, 'itk::Image<unsigned short, 2>, itk::Image<unsigned short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF2ISS2', False, 'itk::Image<float, 2>, itk::Image<signed short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF2IUC2', False, 'itk::Image<float, 2>, itk::Image<unsigned char, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF2IUS2', False, 'itk::Image<float, 2>, itk::Image<unsigned short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID2ISS2', False, 'itk::Image<double, 2>, itk::Image<signed short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID2IUC2', False, 'itk::Image<double, 2>, itk::Image<unsigned char, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID2IUS2', False, 'itk::Image<double, 2>, itk::Image<unsigned short, 2>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS3ISS3', False, 'itk::Image<signed short, 3>, itk::Image<signed short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS3IUC3', False, 'itk::Image<signed short, 3>, itk::Image<unsigned char, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS3IUS3', False, 'itk::Image<signed short, 3>, itk::Image<unsigned short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC3ISS3', False, 'itk::Image<unsigned char, 3>, itk::Image<signed short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC3IUC3', False, 'itk::Image<unsigned char, 3>, itk::Image<unsigned char, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC3IUS3', False, 'itk::Image<unsigned char, 3>, itk::Image<unsigned short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS3ISS3', False, 'itk::Image<unsigned short, 3>, itk::Image<signed short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS3IUC3', False, 'itk::Image<unsigned short, 3>, itk::Image<unsigned char, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS3IUS3', False, 'itk::Image<unsigned short, 3>, itk::Image<unsigned short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF3ISS3', False, 'itk::Image<float, 3>, itk::Image<signed short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF3IUC3', False, 'itk::Image<float, 3>, itk::Image<unsigned char, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF3IUS3', False, 'itk::Image<float, 3>, itk::Image<unsigned short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID3ISS3', False, 'itk::Image<double, 3>, itk::Image<signed short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID3IUC3', False, 'itk::Image<double, 3>, itk::Image<unsigned char, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID3IUS3', False, 'itk::Image<double, 3>, itk::Image<unsigned short, 3>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS4ISS4', False, 'itk::Image<signed short, 4>, itk::Image<signed short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS4IUC4', False, 'itk::Image<signed short, 4>, itk::Image<unsigned char, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVISS4IUS4', False, 'itk::Image<signed short, 4>, itk::Image<unsigned short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC4ISS4', False, 'itk::Image<unsigned char, 4>, itk::Image<signed short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC4IUC4', False, 'itk::Image<unsigned char, 4>, itk::Image<unsigned char, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUC4IUS4', False, 'itk::Image<unsigned char, 4>, itk::Image<unsigned short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS4ISS4', False, 'itk::Image<unsigned short, 4>, itk::Image<signed short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS4IUC4', False, 'itk::Image<unsigned short, 4>, itk::Image<unsigned char, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIUS4IUS4', False, 'itk::Image<unsigned short, 4>, itk::Image<unsigned short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF4ISS4', False, 'itk::Image<float, 4>, itk::Image<signed short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF4IUC4', False, 'itk::Image<float, 4>, itk::Image<unsigned char, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVIF4IUS4', False, 'itk::Image<float, 4>, itk::Image<unsigned short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID4ISS4', False, 'itk::Image<double, 4>, itk::Image<signed short, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID4IUC4', False, 'itk::Image<double, 4>, itk::Image<unsigned char, 4>'),
  ('ConvertImagesToCSV', 'tube::ConvertImagesToCSV', 'tubeConvertImagesToCSVID4IUS4', False, 'itk::Image<double, 4>, itk::Image<unsigned short, 4>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListISS2IVF22', False, 'itk::Image<signed short, 2>, itk::Image<itk::Vector< float,2 >, 2>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIUC2IVF22', False, 'itk::Image<unsigned char, 2>, itk::Image<itk::Vector< float,2 >, 2>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIUS2IVF22', False, 'itk::Image<unsigned short, 2>, itk::Image<itk::Vector< float,2 >, 2>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIF2IVF22', False, 'itk::Image<float, 2>, itk::Image<itk::Vector< float,2 >, 2>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListID2IVF22', False, 'itk::Image<double, 2>, itk::Image<itk::Vector< float,2 >, 2>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListISS3IVF33', False, 'itk::Image<signed short, 3>, itk::Image<itk::Vector< float,3 >, 3>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIUC3IVF33', False, 'itk::Image<unsigned char, 3>, itk::Image<itk::Vector< float,3 >, 3>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIUS3IVF33', False, 'itk::Image<unsigned short, 3>, itk::Image<itk::Vector< float,3 >, 3>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIF3IVF33', False, 'itk::Image<float, 3>, itk::Image<itk::Vector< float,3 >, 3>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListID3IVF33', False, 'itk::Image<double, 3>, itk::Image<itk::Vector< float,3 >, 3>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListISS4IVF44', False, 'itk::Image<signed short, 4>, itk::Image<itk::Vector< float,4 >, 4>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIUC4IVF44', False, 'itk::Image<unsigned char, 4>, itk::Image<itk::Vector< float,4 >, 4>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIUS4IVF44', False, 'itk::Image<unsigned short, 4>, itk::Image<itk::Vector< float,4 >, 4>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListIF4IVF44', False, 'itk::Image<float, 4>, itk::Image<itk::Vector< float,4 >, 4>'),
  ('ConvertShrunkenSeedImageToList', 'tube::ConvertShrunkenSeedImageToList', 'tubeConvertShrunkenSeedImageToListID4IVF44', False, 'itk::Image<double, 4>, itk::Image<itk::Vector< float,4 >, 4>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageISS2ISS2', False, 'itk::Image<signed short, 2>, itk::Image<signed short, 2>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIUC2IUC2', False, 'itk::Image<unsigned char, 2>, itk::Image<unsigned char, 2>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIUS2IUS2', False, 'itk::Image<unsigned short, 2>, itk::Image<unsigned short, 2>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIF2IF2', False, 'itk::Image<float, 2>, itk::Image<float, 2>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageID2ID2', False, 'itk::Image<double, 2>, itk::Image<double, 2>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageISS3ISS3', False, 'itk::Image<signed short, 3>, itk::Image<signed short, 3>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIUC3IUC3', False, 'itk::Image<unsigned char, 3>, itk::Image<unsigned char, 3>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIUS3IUS3', False, 'itk::Image<unsigned short, 3>, itk::Image<unsigned short, 3>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIF3IF3', False, 'itk::Image<float, 3>, itk::Image<float, 3>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageID3ID3', False, 'itk::Image<double, 3>, itk::Image<double, 3>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageISS4ISS4', False, 'itk::Image<signed short, 4>, itk::Image<signed short, 4>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIUC4IUC4', False, 'itk::Image<unsigned char, 4>, itk::Image<unsigned char, 4>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIUS4IUS4', False, 'itk::Image<unsigned short, 4>, itk::Image<unsigned short, 4>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageIF4IF4', False, 'itk::Image<float, 4>, itk::Image<float, 4>'),
  ('ConvertSpatialGraphToImage', 'tube::ConvertSpatialGraphToImage', 'tubeConvertSpatialGraphToImageID4ID4', False, 'itk::Image<double, 4>, itk::Image<double, 4>'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageSS2', False, 'signed short, 2'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageUC2', False, 'unsigned char, 2'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageUS2', False, 'unsigned short, 2'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageF2', False, 'float, 2'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageD2', False, 'double, 2'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageSS3', False, 'signed short, 3'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageUC3', False, 'unsigned char, 3'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageUS3', False, 'unsigned short, 3'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageF3', False, 'float, 3'),
  ('ConvertTubesToDensityImage', 'tube::ConvertTubesToDensityImage', 'tubeConvertTubesToDensityImageD3', False, 'double, 3'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageSS2', False, 'itk::Image<signed short,2>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageUC2', False, 'itk::Image<unsigned char,2>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageUS2', False, 'itk::Image<unsigned short,2>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageF2', False, 'itk::Image<float,2>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageD2', False, 'itk::Image<double,2>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageSS3', False, 'itk::Image<signed short,3>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageUC3', False, 'itk::Image<unsigned char,3>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageUS3', False, 'itk::Image<unsigned short,3>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageF3', False, 'itk::Image<float,3>'),
  ('ConvertTubesToImage', 'tube::ConvertTubesToImage', 'tubeConvertTubesToImageD3', False, 'itk::Image<double,3>'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphSS2', False, 'signed short, 2'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphUC2', False, 'unsigned char, 2'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphUS2', False, 'unsigned short, 2'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphF2', False, 'float, 2'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphD2', False, 'double, 2'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphSS3', False, 'signed short, 3'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphUC3', False, 'unsigned char, 3'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphUS3', False, 'unsigned short, 3'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphF3', False, 'float, 3'),
  ('ConvertTubesToTubeGraph', 'tube::ConvertTubesToTubeGraph', 'tubeConvertTubesToTubeGraphD3', False, 'double, 3'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSSS2', False, 'itk::Image<signed short,2>,itk::Image<signed short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSSS3', False, 'itk::Image<signed short,3>,itk::Image<signed short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSUC2', False, 'itk::Image<signed short,2>,itk::Image<unsigned char,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSUC3', False, 'itk::Image<signed short,3>,itk::Image<unsigned char,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSUS2', False, 'itk::Image<signed short,2>,itk::Image<unsigned short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSUS3', False, 'itk::Image<signed short,3>,itk::Image<unsigned short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSF2', False, 'itk::Image<signed short,2>,itk::Image<float,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSF3', False, 'itk::Image<signed short,3>,itk::Image<float,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSD2', False, 'itk::Image<signed short,2>,itk::Image<double,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageSSD3', False, 'itk::Image<signed short,3>,itk::Image<double,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCSS2', False, 'itk::Image<unsigned char,2>,itk::Image<signed short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCSS3', False, 'itk::Image<unsigned char,3>,itk::Image<signed short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCUC2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned char,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCUC3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned char,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCUS2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCUS3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCF2', False, 'itk::Image<unsigned char,2>,itk::Image<float,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCF3', False, 'itk::Image<unsigned char,3>,itk::Image<float,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCD2', False, 'itk::Image<unsigned char,2>,itk::Image<double,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUCD3', False, 'itk::Image<unsigned char,3>,itk::Image<double,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSSS2', False, 'itk::Image<unsigned short,2>,itk::Image<signed short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSSS3', False, 'itk::Image<unsigned short,3>,itk::Image<signed short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSUC2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned char,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSUC3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned char,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSUS2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSUS3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSF2', False, 'itk::Image<unsigned short,2>,itk::Image<float,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSF3', False, 'itk::Image<unsigned short,3>,itk::Image<float,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSD2', False, 'itk::Image<unsigned short,2>,itk::Image<double,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageUSD3', False, 'itk::Image<unsigned short,3>,itk::Image<double,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFSS2', False, 'itk::Image<float,2>,itk::Image<signed short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFSS3', False, 'itk::Image<float,3>,itk::Image<signed short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFUC2', False, 'itk::Image<float,2>,itk::Image<unsigned char,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFUC3', False, 'itk::Image<float,3>,itk::Image<unsigned char,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFUS2', False, 'itk::Image<float,2>,itk::Image<unsigned short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFUS3', False, 'itk::Image<float,3>,itk::Image<unsigned short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFF2', False, 'itk::Image<float,2>,itk::Image<float,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFF3', False, 'itk::Image<float,3>,itk::Image<float,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFD2', False, 'itk::Image<float,2>,itk::Image<double,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageFD3', False, 'itk::Image<float,3>,itk::Image<double,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDSS2', False, 'itk::Image<double,2>,itk::Image<signed short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDSS3', False, 'itk::Image<double,3>,itk::Image<signed short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDUC2', False, 'itk::Image<double,2>,itk::Image<unsigned char,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDUC3', False, 'itk::Image<double,3>,itk::Image<unsigned char,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDUS2', False, 'itk::Image<double,2>,itk::Image<unsigned short,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDUS3', False, 'itk::Image<double,3>,itk::Image<unsigned short,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDF2', False, 'itk::Image<double,2>,itk::Image<float,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDF3', False, 'itk::Image<double,3>,itk::Image<float,3>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDD2', False, 'itk::Image<double,2>,itk::Image<double,2>'),
  ('CropImage', 'tube::CropImage', 'tubeCropImageDD3', False, 'itk::Image<double,3>,itk::Image<double,3>'),
  ('CropTubes', 'tube::CropTubes', 'tubeCropTubes2', False, '2'),
  ('CropTubes', 'tube::CropTubes', 'tubeCropTubes3', False, '3'),
  ('CropTubes', 'tube::CropTubes', 'tubeCropTubes4', False, '4'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorSS2', False, 'signed short, 2'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorSS3', False, 'signed short, 3'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorUC2', False, 'unsigned char, 2'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorUC3', False, 'unsigned char, 3'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorUS2', False, 'unsigned short, 2'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorUS3', False, 'unsigned short, 3'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorF2', False, 'float, 2'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorF3', False, 'float, 3'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorD2', False, 'double, 2'),
  ('EnhanceContrastUsingPrior', 'tube::EnhanceContrastUsingPrior', 'tubeEnhanceContrastUsingPriorD3', False, 'double, 3'),
  ('EnhanceEdgesUsingDiffusion', 'tube::EnhanceEdgesUsingDiffusion', 'tubeEnhanceEdgesUsingDiffusionIF3IF3', False, 'itk::Image<float, 3>, itk::Image<float, 3>'),
  ('EnhanceEdgesUsingDiffusion', 'tube::EnhanceEdgesUsingDiffusion', 'tubeEnhanceEdgesUsingDiffusionID3ID3', False, 'itk::Image<double, 3>, itk::Image<double, 3>'),
  ('EnhanceTubesUsingDiffusion', 'tube::EnhanceTubesUsingDiffusion', 'tubeEnhanceTubesUsingDiffusionSS2', False, 'signed short, 2'),
  ('EnhanceTubesUsingDiffusion', 'tube::EnhanceTubesUsingDiffusion', 'tubeEnhanceTubesUsingDiffusionUC2', False, 'unsigned char, 2'),
  ('EnhanceTubesUsingDiffusion', 'tube::EnhanceTubesUsingDiffusion', 'tubeEnhanceTubesUsingDiffusionUS2', False, 'unsigned short, 2'),
  ('EnhanceTubesUsingDiffusion', 'tube::EnhanceTubesUsingDiffusion', 'tubeEnhanceTubesUsingDiffusionF2', False, 'float, 2'),
  ('EnhanceTubesUsingDiffusion', 'tube::EnhanceTubesUsingDiffusion', 'tubeEnhanceTubesUsingDiffusionD2', False, 'double, 2'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSSS2', False, 'itk::Image<signed short,2>,itk::Image<signed short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSUC2', False, 'itk::Image<signed short,2>,itk::Image<unsigned char,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSUS2', False, 'itk::Image<signed short,2>,itk::Image<unsigned short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSF2', False, 'itk::Image<signed short,2>,itk::Image<float,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSD2', False, 'itk::Image<signed short,2>,itk::Image<double,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCSS2', False, 'itk::Image<unsigned char,2>,itk::Image<signed short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCUC2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned char,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCUS2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCF2', False, 'itk::Image<unsigned char,2>,itk::Image<float,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCD2', False, 'itk::Image<unsigned char,2>,itk::Image<double,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSSS2', False, 'itk::Image<unsigned short,2>,itk::Image<signed short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSUC2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned char,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSUS2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSF2', False, 'itk::Image<unsigned short,2>,itk::Image<float,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSD2', False, 'itk::Image<unsigned short,2>,itk::Image<double,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFSS2', False, 'itk::Image<float,2>,itk::Image<signed short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFUC2', False, 'itk::Image<float,2>,itk::Image<unsigned char,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFUS2', False, 'itk::Image<float,2>,itk::Image<unsigned short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFF2', False, 'itk::Image<float,2>,itk::Image<float,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFD2', False, 'itk::Image<float,2>,itk::Image<double,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDSS2', False, 'itk::Image<double,2>,itk::Image<signed short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDUC2', False, 'itk::Image<double,2>,itk::Image<unsigned char,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDUS2', False, 'itk::Image<double,2>,itk::Image<unsigned short,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDF2', False, 'itk::Image<double,2>,itk::Image<float,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDD2', False, 'itk::Image<double,2>,itk::Image<double,2>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSSS3', False, 'itk::Image<signed short,3>,itk::Image<signed short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSUC3', False, 'itk::Image<signed short,3>,itk::Image<unsigned char,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSUS3', False, 'itk::Image<signed short,3>,itk::Image<unsigned short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSF3', False, 'itk::Image<signed short,3>,itk::Image<float,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSD3', False, 'itk::Image<signed short,3>,itk::Image<double,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCSS3', False, 'itk::Image<unsigned char,3>,itk::Image<signed short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCUC3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned char,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCUS3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCF3', False, 'itk::Image<unsigned char,3>,itk::Image<float,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCD3', False, 'itk::Image<unsigned char,3>,itk::Image<double,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSSS3', False, 'itk::Image<unsigned short,3>,itk::Image<signed short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSUC3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned char,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSUS3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSF3', False, 'itk::Image<unsigned short,3>,itk::Image<float,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSD3', False, 'itk::Image<unsigned short,3>,itk::Image<double,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFSS3', False, 'itk::Image<float,3>,itk::Image<signed short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFUC3', False, 'itk::Image<float,3>,itk::Image<unsigned char,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFUS3', False, 'itk::Image<float,3>,itk::Image<unsigned short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFF3', False, 'itk::Image<float,3>,itk::Image<float,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFD3', False, 'itk::Image<float,3>,itk::Image<double,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDSS3', False, 'itk::Image<double,3>,itk::Image<signed short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDUC3', False, 'itk::Image<double,3>,itk::Image<unsigned char,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDUS3', False, 'itk::Image<double,3>,itk::Image<unsigned short,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDF3', False, 'itk::Image<double,3>,itk::Image<float,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDD3', False, 'itk::Image<double,3>,itk::Image<double,3>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSSS4', False, 'itk::Image<signed short,4>,itk::Image<signed short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSUC4', False, 'itk::Image<signed short,4>,itk::Image<unsigned char,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSUS4', False, 'itk::Image<signed short,4>,itk::Image<unsigned short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSF4', False, 'itk::Image<signed short,4>,itk::Image<float,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisSSD4', False, 'itk::Image<signed short,4>,itk::Image<double,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCSS4', False, 'itk::Image<unsigned char,4>,itk::Image<signed short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCUC4', False, 'itk::Image<unsigned char,4>,itk::Image<unsigned char,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCUS4', False, 'itk::Image<unsigned char,4>,itk::Image<unsigned short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCF4', False, 'itk::Image<unsigned char,4>,itk::Image<float,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUCD4', False, 'itk::Image<unsigned char,4>,itk::Image<double,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSSS4', False, 'itk::Image<unsigned short,4>,itk::Image<signed short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSUC4', False, 'itk::Image<unsigned short,4>,itk::Image<unsigned char,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSUS4', False, 'itk::Image<unsigned short,4>,itk::Image<unsigned short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSF4', False, 'itk::Image<unsigned short,4>,itk::Image<float,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisUSD4', False, 'itk::Image<unsigned short,4>,itk::Image<double,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFSS4', False, 'itk::Image<float,4>,itk::Image<signed short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFUC4', False, 'itk::Image<float,4>,itk::Image<unsigned char,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFUS4', False, 'itk::Image<float,4>,itk::Image<unsigned short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFF4', False, 'itk::Image<float,4>,itk::Image<float,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisFD4', False, 'itk::Image<float,4>,itk::Image<double,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDSS4', False, 'itk::Image<double,4>,itk::Image<signed short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDUC4', False, 'itk::Image<double,4>,itk::Image<unsigned char,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDUS4', False, 'itk::Image<double,4>,itk::Image<unsigned short,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDF4', False, 'itk::Image<double,4>,itk::Image<float,4>'),
  ('EnhanceTubesUsingDiscriminantAnalysis', 'tube::EnhanceTubesUsingDiscriminantAnalysis', 'tubeEnhanceTubesUsingDiscriminantAnalysisDD4', False, 'itk::Image<double,4>,itk::Image<double,4>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathSS2', False, 'itk::Image<signed short,2>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathSS3', False, 'itk::Image<signed short,3>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathUC2', False, 'itk::Image<unsigned char,2>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathUC3', False, 'itk::Image<unsigned char,3>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathUS2', False, 'itk::Image<unsigned short,2>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathUS3', False, 'itk::Image<unsigned short,3>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathF2', False, 'itk::Image<float,2>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathF3', False, 'itk::Image<float,3>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathD2', False, 'itk::Image<double,2>'),
  ('ImageMath', 'tube::ImageMath', 'tubeImageMathD3', False, 'itk::Image<double,3>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesISS2', False, 'itk::Image<signed short, 2>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesISS3', False, 'itk::Image<signed short, 3>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesIUC2', False, 'itk::Image<unsigned char, 2>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesIUC3', False, 'itk::Image<unsigned char, 3>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesIUS2', False, 'itk::Image<unsigned short, 2>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesIUS3', False, 'itk::Image<unsigned short, 3>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesIF2', False, 'itk::Image<float, 2>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesIF3', False, 'itk::Image<float, 3>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesID2', False, 'itk::Image<double, 2>'),
  ('MergeAdjacentImages', 'tube::MergeAdjacentImages', 'tubeMergeAdjacentImagesID3', False, 'itk::Image<double, 3>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesSS2', False, 'itk::Image<signed short,2>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesSS3', False, 'itk::Image<signed short,3>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesUC2', False, 'itk::Image<unsigned char,2>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesUC3', False, 'itk::Image<unsigned char,3>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesUS2', False, 'itk::Image<unsigned short,2>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesUS3', False, 'itk::Image<unsigned short,3>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesF2', False, 'itk::Image<float,2>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesF3', False, 'itk::Image<float,3>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesD2', False, 'itk::Image<double,2>'),
  ('RegisterImages', 'tube::RegisterImages', 'tubeRegisterImagesD3', False, 'itk::Image<double,3>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageSS2', False, 'itk::Image<signed short,2>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageSS3', False, 'itk::Image<signed short,3>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageUC2', False, 'itk::Image<unsigned char,2>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageUC3', False, 'itk::Image<unsigned char,3>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageUS2', False, 'itk::Image<unsigned short,2>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageUS3', False, 'itk::Image<unsigned short,3>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageF2', False, 'itk::Image<float,2>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageF3', False, 'itk::Image<float,3>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageD2', False, 'itk::Image<double,2>'),
  ('ResampleImage', 'tube::ResampleImage', 'tubeResampleImageD3', False, 'itk::Image<double,3>'),
  ('SegmentBinaryImageSkeleton3D', 'tube::SegmentBinaryImageSkeleton3D', 'tubeSegmentBinaryImageSkeleton3DSS', False, 'itk::Image<signed short, 3>'),
  ('SegmentBinaryImageSkeleton3D', 'tube::SegmentBinaryImageSkeleton3D', 'tubeSegmentBinaryImageSkeleton3DUC', False, 'itk::Image<unsigned char, 3>'),
  ('SegmentBinaryImageSkeleton3D', 'tube::SegmentBinaryImageSkeleton3D', 'tubeSegmentBinaryImageSkeleton3DUS', False, 'itk::Image<unsigned short, 3>'),
  ('SegmentBinaryImageSkeleton3D', 'tube::SegmentBinaryImageSkeleton3D', 'tubeSegmentBinaryImageSkeleton3DF', False, 'itk::Image<float, 3>'),
  ('SegmentBinaryImageSkeleton3D', 'tube::SegmentBinaryImageSkeleton3D', 'tubeSegmentBinaryImageSkeleton3DD', False, 'itk::Image<double, 3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsSSSS2', False, 'itk::Image<signed short,2>,itk::Image<signed short,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsSSSS3', False, 'itk::Image<signed short,3>,itk::Image<signed short,3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsSSUC2', False, 'itk::Image<signed short,2>,itk::Image<unsigned char,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsSSUC3', False, 'itk::Image<signed short,3>,itk::Image<unsigned char,3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsSSUS2', False, 'itk::Image<signed short,2>,itk::Image<unsigned short,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsSSUS3', False, 'itk::Image<signed short,3>,itk::Image<unsigned short,3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUCSS2', False, 'itk::Image<unsigned char,2>,itk::Image<signed short,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUCSS3', False, 'itk::Image<unsigned char,3>,itk::Image<signed short,3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUCUC2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned char,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUCUC3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned char,3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUCUS2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned short,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUCUS3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned short,3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUSSS2', False, 'itk::Image<unsigned short,2>,itk::Image<signed short,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUSSS3', False, 'itk::Image<unsigned short,3>,itk::Image<signed short,3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUSUC2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned char,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUSUC3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned char,3>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUSUS2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned short,2>'),
  ('SegmentConnectedComponents', 'tube::SegmentConnectedComponents', 'tubeSegmentConnectedComponentsUSUS3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSSS2', False, 'itk::Image<signed short,2>,itk::Image<signed short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSSS3', False, 'itk::Image<signed short,3>,itk::Image<signed short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSUC2', False, 'itk::Image<signed short,2>,itk::Image<unsigned char,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSUC3', False, 'itk::Image<signed short,3>,itk::Image<unsigned char,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSUS2', False, 'itk::Image<signed short,2>,itk::Image<unsigned short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSUS3', False, 'itk::Image<signed short,3>,itk::Image<unsigned short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSF2', False, 'itk::Image<signed short,2>,itk::Image<float,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSF3', False, 'itk::Image<signed short,3>,itk::Image<float,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSD2', False, 'itk::Image<signed short,2>,itk::Image<double,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsSSD3', False, 'itk::Image<signed short,3>,itk::Image<double,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCSS2', False, 'itk::Image<unsigned char,2>,itk::Image<signed short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCSS3', False, 'itk::Image<unsigned char,3>,itk::Image<signed short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCUC2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned char,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCUC3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned char,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCUS2', False, 'itk::Image<unsigned char,2>,itk::Image<unsigned short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCUS3', False, 'itk::Image<unsigned char,3>,itk::Image<unsigned short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCF2', False, 'itk::Image<unsigned char,2>,itk::Image<float,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCF3', False, 'itk::Image<unsigned char,3>,itk::Image<float,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCD2', False, 'itk::Image<unsigned char,2>,itk::Image<double,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUCD3', False, 'itk::Image<unsigned char,3>,itk::Image<double,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSSS2', False, 'itk::Image<unsigned short,2>,itk::Image<signed short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSSS3', False, 'itk::Image<unsigned short,3>,itk::Image<signed short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSUC2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned char,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSUC3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned char,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSUS2', False, 'itk::Image<unsigned short,2>,itk::Image<unsigned short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSUS3', False, 'itk::Image<unsigned short,3>,itk::Image<unsigned short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSF2', False, 'itk::Image<unsigned short,2>,itk::Image<float,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSF3', False, 'itk::Image<unsigned short,3>,itk::Image<float,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSD2', False, 'itk::Image<unsigned short,2>,itk::Image<double,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsUSD3', False, 'itk::Image<unsigned short,3>,itk::Image<double,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFSS2', False, 'itk::Image<float,2>,itk::Image<signed short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFSS3', False, 'itk::Image<float,3>,itk::Image<signed short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFUC2', False, 'itk::Image<float,2>,itk::Image<unsigned char,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFUC3', False, 'itk::Image<float,3>,itk::Image<unsigned char,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFUS2', False, 'itk::Image<float,2>,itk::Image<unsigned short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFUS3', False, 'itk::Image<float,3>,itk::Image<unsigned short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFF2', False, 'itk::Image<float,2>,itk::Image<float,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFF3', False, 'itk::Image<float,3>,itk::Image<float,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFD2', False, 'itk::Image<float,2>,itk::Image<double,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsFD3', False, 'itk::Image<float,3>,itk::Image<double,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDSS2', False, 'itk::Image<double,2>,itk::Image<signed short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDSS3', False, 'itk::Image<double,3>,itk::Image<signed short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDUC2', False, 'itk::Image<double,2>,itk::Image<unsigned char,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDUC3', False, 'itk::Image<double,3>,itk::Image<unsigned char,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDUS2', False, 'itk::Image<double,2>,itk::Image<unsigned short,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDUS3', False, 'itk::Image<double,3>,itk::Image<unsigned short,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDF2', False, 'itk::Image<double,2>,itk::Image<float,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDF3', False, 'itk::Image<double,3>,itk::Image<float,3>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDD2', False, 'itk::Image<double,2>,itk::Image<double,2>'),
  ('SegmentConnectedComponentsUsingParzenPDFs', 'tube::SegmentConnectedComponentsUsingParzenPDFs', 'tubeSegmentConnectedComponentsUsingParzenPDFsDD3', False, 'itk::Image<double,3>,itk::Image<double,3>'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath2SS', False, '2, signed short'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath2UC', False, '2, unsigned char'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath2US', False, '2, unsigned short'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath2F', False, '2, float'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath2D', False, '2, double'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath3SS', False, '3, signed short'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath3UC', False, '3, unsigned char'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath3US', False, '3, unsigned short'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath3F', False, '3, float'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath3D', False, '3, double'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath4SS', False, '4, signed short'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath4UC', False, '4, unsigned char'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath4US', False, '4, unsigned short'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath4F', False, '4, float'),
  ('SegmentTubeUsingMinimalPath', 'tube::SegmentTubeUsingMinimalPath', 'tubeSegmentTubeUsingMinimalPath4D', False, '4, double'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesISS2', False, 'itk::Image<signed short, 2>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIUC2', False, 'itk::Image<unsigned char, 2>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIUS2', False, 'itk::Image<unsigned short, 2>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIF2', False, 'itk::Image<float, 2>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesID2', False, 'itk::Image<double, 2>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesISS3', False, 'itk::Image<signed short, 3>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIUC3', False, 'itk::Image<unsigned char, 3>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIUS3', False, 'itk::Image<unsigned short, 3>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIF3', False, 'itk::Image<float, 3>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesID3', False, 'itk::Image<double, 3>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesISS4', False, 'itk::Image<signed short, 4>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIUC4', False, 'itk::Image<unsigned char, 4>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIUS4', False, 'itk::Image<unsigned short, 4>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesIF4', False, 'itk::Image<float, 4>'),
  ('SegmentTubes', 'tube::SegmentTubes', 'tubeSegmentTubesID4', False, 'itk::Image<double, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS2SS', False, 'itk::Image<signed short, 2>, itk::Image<signed short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS2UC', False, 'itk::Image<signed short, 2>, itk::Image<unsigned char, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS2US', False, 'itk::Image<signed short, 2>, itk::Image<unsigned short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS3SS', False, 'itk::Image<signed short, 3>, itk::Image<signed short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS3UC', False, 'itk::Image<signed short, 3>, itk::Image<unsigned char, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS3US', False, 'itk::Image<signed short, 3>, itk::Image<unsigned short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS4SS', False, 'itk::Image<signed short, 4>, itk::Image<signed short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS4UC', False, 'itk::Image<signed short, 4>, itk::Image<unsigned char, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdSS4US', False, 'itk::Image<signed short, 4>, itk::Image<unsigned short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC2SS', False, 'itk::Image<unsigned char, 2>, itk::Image<signed short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC2UC', False, 'itk::Image<unsigned char, 2>, itk::Image<unsigned char, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC2US', False, 'itk::Image<unsigned char, 2>, itk::Image<unsigned short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC3SS', False, 'itk::Image<unsigned char, 3>, itk::Image<signed short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC3UC', False, 'itk::Image<unsigned char, 3>, itk::Image<unsigned char, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC3US', False, 'itk::Image<unsigned char, 3>, itk::Image<unsigned short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC4SS', False, 'itk::Image<unsigned char, 4>, itk::Image<signed short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC4UC', False, 'itk::Image<unsigned char, 4>, itk::Image<unsigned char, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUC4US', False, 'itk::Image<unsigned char, 4>, itk::Image<unsigned short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS2SS', False, 'itk::Image<unsigned short, 2>, itk::Image<signed short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS2UC', False, 'itk::Image<unsigned short, 2>, itk::Image<unsigned char, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS2US', False, 'itk::Image<unsigned short, 2>, itk::Image<unsigned short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS3SS', False, 'itk::Image<unsigned short, 3>, itk::Image<signed short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS3UC', False, 'itk::Image<unsigned short, 3>, itk::Image<unsigned char, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS3US', False, 'itk::Image<unsigned short, 3>, itk::Image<unsigned short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS4SS', False, 'itk::Image<unsigned short, 4>, itk::Image<signed short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS4UC', False, 'itk::Image<unsigned short, 4>, itk::Image<unsigned char, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdUS4US', False, 'itk::Image<unsigned short, 4>, itk::Image<unsigned short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF2SS', False, 'itk::Image<float, 2>, itk::Image<signed short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF2UC', False, 'itk::Image<float, 2>, itk::Image<unsigned char, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF2US', False, 'itk::Image<float, 2>, itk::Image<unsigned short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF3SS', False, 'itk::Image<float, 3>, itk::Image<signed short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF3UC', False, 'itk::Image<float, 3>, itk::Image<unsigned char, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF3US', False, 'itk::Image<float, 3>, itk::Image<unsigned short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF4SS', False, 'itk::Image<float, 4>, itk::Image<signed short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF4UC', False, 'itk::Image<float, 4>, itk::Image<unsigned char, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdF4US', False, 'itk::Image<float, 4>, itk::Image<unsigned short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD2SS', False, 'itk::Image<double, 2>, itk::Image<signed short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD2UC', False, 'itk::Image<double, 2>, itk::Image<unsigned char, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD2US', False, 'itk::Image<double, 2>, itk::Image<unsigned short, 2>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD3SS', False, 'itk::Image<double, 3>, itk::Image<signed short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD3UC', False, 'itk::Image<double, 3>, itk::Image<unsigned char, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD3US', False, 'itk::Image<double, 3>, itk::Image<unsigned short, 3>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD4SS', False, 'itk::Image<double, 4>, itk::Image<signed short, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD4UC', False, 'itk::Image<double, 4>, itk::Image<unsigned char, 4>'),
  ('SegmentUsingOtsuThreshold', 'tube::SegmentUsingOtsuThreshold', 'tubeSegmentUsingOtsuThresholdD4US', False, 'itk::Image<double, 4>, itk::Image<unsigned short, 4>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingISS2ISS2', False, 'itk::Image<signed short, 2>, itk::Image<signed short, 2>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIUC2IUC2', False, 'itk::Image<unsigned char, 2>, itk::Image<unsigned char, 2>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIUS2IUS2', False, 'itk::Image<unsigned short, 2>, itk::Image<unsigned short, 2>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIF2IF2', False, 'itk::Image<float, 2>, itk::Image<float, 2>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingID2ID2', False, 'itk::Image<double, 2>, itk::Image<double, 2>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingISS3ISS3', False, 'itk::Image<signed short, 3>, itk::Image<signed short, 3>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIUC3IUC3', False, 'itk::Image<unsigned char, 3>, itk::Image<unsigned char, 3>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIUS3IUS3', False, 'itk::Image<unsigned short, 3>, itk::Image<unsigned short, 3>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIF3IF3', False, 'itk::Image<float, 3>, itk::Image<float, 3>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingID3ID3', False, 'itk::Image<double, 3>, itk::Image<double, 3>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingISS4ISS4', False, 'itk::Image<signed short, 4>, itk::Image<signed short, 4>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIUC4IUC4', False, 'itk::Image<unsigned char, 4>, itk::Image<unsigned char, 4>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIUS4IUS4', False, 'itk::Image<unsigned short, 4>, itk::Image<unsigned short, 4>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingIF4IF4', False, 'itk::Image<float, 4>, itk::Image<float, 4>'),
  ('ShrinkImageWithBlending', 'tube::ShrinkImageWithBlending', 'tubeShrinkImageWithBlendingID4ID4', False, 'itk::Image<double, 4>, itk::Image<double, 4>'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath2SS', False, '2,signed short'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath3SS', False, '3,signed short'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath2UC', False, '2,unsigned char'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath3UC', False, '3,unsigned char'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath2US', False, '2,unsigned short'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath3US', False, '3,unsigned short'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath2F', False, '2,float'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath3F', False, '3,float'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath2D', False, '2,double'),
  ('TubeMath', 'tube::TubeMath', 'tubeTubeMath3D', False, '3,double'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesSS2', False, 'itk::Image<signed short,2>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesSS3', False, 'itk::Image<signed short,3>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesUC2', False, 'itk::Image<unsigned char,2>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesUC3', False, 'itk::Image<unsigned char,3>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesUS2', False, 'itk::Image<unsigned short,2>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesUS3', False, 'itk::Image<unsigned short,3>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesF2', False, 'itk::Image<float,2>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesF3', False, 'itk::Image<float,3>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesD2', False, 'itk::Image<double,2>'),
  ('Write4DImageFrom3DImages', 'tube::Write4DImageFrom3DImages', 'tubeWrite4DImageFrom3DImagesD3', False, 'itk::Image<double,3>'),
)
factories = ()
