# Generated by Django 3.2.15 on 2022-08-21 17:00
import django.core.serializers.json
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('gisdo', '0012_groupdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdata',
            name='data',
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Данные группы'
            ),
        ),
    ]
