import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_c4c870b8e7(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_6fe294b485():spartaqube_cli.list()
@app.command()
def sparta_b9524e096c():spartaqube_cli.sparta_b9524e096c()
@app.command()
def sparta_702270dc65():print('Hello world!')
if __name__=='__main__':app()