# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgLib.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cMsgLib.proto\x1a\x19google/protobuf/any.proto\"A\n\x0bmsgEnvelope\x12\x0f\n\x07msgName\x18\x01 \x01(\t\x12!\n\x03msg\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"D\n\x0fRegisterService\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0e\n\x06server\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"F\n\x11UnregisterService\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0e\n\x06server\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"\x11\n\x03\x61\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x0f\n\rRediscoverReq\"\'\n\x10ServiceLookupReq\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\"E\n\x10ServiceLookupRep\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0e\n\x06server\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"\x0f\n\rShutdownEvent\"\x17\n\tHeartbeat\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')



_MSGENVELOPE = DESCRIPTOR.message_types_by_name['msgEnvelope']
_REGISTERSERVICE = DESCRIPTOR.message_types_by_name['RegisterService']
_UNREGISTERSERVICE = DESCRIPTOR.message_types_by_name['UnregisterService']
_ACK = DESCRIPTOR.message_types_by_name['ack']
_REDISCOVERREQ = DESCRIPTOR.message_types_by_name['RediscoverReq']
_SERVICELOOKUPREQ = DESCRIPTOR.message_types_by_name['ServiceLookupReq']
_SERVICELOOKUPREP = DESCRIPTOR.message_types_by_name['ServiceLookupRep']
_SHUTDOWNEVENT = DESCRIPTOR.message_types_by_name['ShutdownEvent']
_HEARTBEAT = DESCRIPTOR.message_types_by_name['Heartbeat']
msgEnvelope = _reflection.GeneratedProtocolMessageType('msgEnvelope', (_message.Message,), {
  'DESCRIPTOR' : _MSGENVELOPE,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:msgEnvelope)
  })
_sym_db.RegisterMessage(msgEnvelope)

RegisterService = _reflection.GeneratedProtocolMessageType('RegisterService', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERSERVICE,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:RegisterService)
  })
_sym_db.RegisterMessage(RegisterService)

UnregisterService = _reflection.GeneratedProtocolMessageType('UnregisterService', (_message.Message,), {
  'DESCRIPTOR' : _UNREGISTERSERVICE,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:UnregisterService)
  })
_sym_db.RegisterMessage(UnregisterService)

ack = _reflection.GeneratedProtocolMessageType('ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:ack)
  })
_sym_db.RegisterMessage(ack)

RediscoverReq = _reflection.GeneratedProtocolMessageType('RediscoverReq', (_message.Message,), {
  'DESCRIPTOR' : _REDISCOVERREQ,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:RediscoverReq)
  })
_sym_db.RegisterMessage(RediscoverReq)

ServiceLookupReq = _reflection.GeneratedProtocolMessageType('ServiceLookupReq', (_message.Message,), {
  'DESCRIPTOR' : _SERVICELOOKUPREQ,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:ServiceLookupReq)
  })
_sym_db.RegisterMessage(ServiceLookupReq)

ServiceLookupRep = _reflection.GeneratedProtocolMessageType('ServiceLookupRep', (_message.Message,), {
  'DESCRIPTOR' : _SERVICELOOKUPREP,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:ServiceLookupRep)
  })
_sym_db.RegisterMessage(ServiceLookupRep)

ShutdownEvent = _reflection.GeneratedProtocolMessageType('ShutdownEvent', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNEVENT,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:ShutdownEvent)
  })
_sym_db.RegisterMessage(ShutdownEvent)

Heartbeat = _reflection.GeneratedProtocolMessageType('Heartbeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'MsgLib_pb2'
  # @@protoc_insertion_point(class_scope:Heartbeat)
  })
_sym_db.RegisterMessage(Heartbeat)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSGENVELOPE._serialized_start=43
  _MSGENVELOPE._serialized_end=108
  _REGISTERSERVICE._serialized_start=110
  _REGISTERSERVICE._serialized_end=178
  _UNREGISTERSERVICE._serialized_start=180
  _UNREGISTERSERVICE._serialized_end=250
  _ACK._serialized_start=252
  _ACK._serialized_end=269
  _REDISCOVERREQ._serialized_start=271
  _REDISCOVERREQ._serialized_end=286
  _SERVICELOOKUPREQ._serialized_start=288
  _SERVICELOOKUPREQ._serialized_end=327
  _SERVICELOOKUPREP._serialized_start=329
  _SERVICELOOKUPREP._serialized_end=398
  _SHUTDOWNEVENT._serialized_start=400
  _SHUTDOWNEVENT._serialized_end=415
  _HEARTBEAT._serialized_start=417
  _HEARTBEAT._serialized_end=440
# @@protoc_insertion_point(module_scope)
