# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.api.blockchains_assets_beta_api import BlockchainsAssetsBetaApi


class TestBlockchainsAssetsBetaApi(unittest.TestCase):
    """BlockchainsAssetsBetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlockchainsAssetsBetaApi()

    def tearDown(self) -> None:
        pass

    def test_get_asset_by_id(self) -> None:
        """Test case for get_asset_by_id

        Get an asset
        """
        pass

    def test_get_blockchain_by_id(self) -> None:
        """Test case for get_blockchain_by_id

        Get an blockchain
        """
        pass

    def test_list_assets(self) -> None:
        """Test case for list_assets

        List assets
        """
        pass

    def test_list_blockchains(self) -> None:
        """Test case for list_blockchains

        List blockchains
        """
        pass


if __name__ == "__main__":
    unittest.main()
