__title__ = "pyavrio"
__description__ = "Python client library for Avrio"
__url__ = "https://github.com/avrioproductionsupport/pyavrio"
__version__ = "20.0.3"
__author__ = "Avrio Team"
__author_email__ = "avrioproductionsupport@trianz.com"
