# coding: utf-8

"""
Defect Dojo API v2

Defect Dojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

The version of the OpenAPI document: 2.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from defectdojo_api_generated.api.test_imports_api import TestImportsApi


class TestTestImportsApi(unittest.TestCase):
    """TestImportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestImportsApi()

    def tearDown(self) -> None:
        pass

    def test_test_imports_create(self) -> None:
        """Test case for test_imports_create"""
        pass

    def test_test_imports_delete_preview_list(self) -> None:
        """Test case for test_imports_delete_preview_list"""
        pass

    def test_test_imports_destroy(self) -> None:
        """Test case for test_imports_destroy"""
        pass

    def test_test_imports_list(self) -> None:
        """Test case for test_imports_list"""
        pass

    def test_test_imports_partial_update(self) -> None:
        """Test case for test_imports_partial_update"""
        pass

    def test_test_imports_retrieve(self) -> None:
        """Test case for test_imports_retrieve"""
        pass

    def test_test_imports_update(self) -> None:
        """Test case for test_imports_update"""
        pass


if __name__ == '__main__':
    unittest.main()
