# coding: utf-8

"""
Defect Dojo API v2

Defect Dojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

The version of the OpenAPI document: 2.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from defectdojo_api_generated.api.risk_acceptance_api import RiskAcceptanceApi


class TestRiskAcceptanceApi(unittest.TestCase):
    """RiskAcceptanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RiskAcceptanceApi()

    def tearDown(self) -> None:
        pass

    def test_risk_acceptance_create(self) -> None:
        """Test case for risk_acceptance_create"""
        pass

    def test_risk_acceptance_delete_preview_list(self) -> None:
        """Test case for risk_acceptance_delete_preview_list"""
        pass

    def test_risk_acceptance_destroy(self) -> None:
        """Test case for risk_acceptance_destroy"""
        pass

    def test_risk_acceptance_download_proof_retrieve(self) -> None:
        """Test case for risk_acceptance_download_proof_retrieve"""
        pass

    def test_risk_acceptance_list(self) -> None:
        """Test case for risk_acceptance_list"""
        pass

    def test_risk_acceptance_partial_update(self) -> None:
        """Test case for risk_acceptance_partial_update"""
        pass

    def test_risk_acceptance_retrieve(self) -> None:
        """Test case for risk_acceptance_retrieve"""
        pass

    def test_risk_acceptance_update(self) -> None:
        """Test case for risk_acceptance_update"""
        pass


if __name__ == '__main__':
    unittest.main()
