# coding: utf-8

"""
Defect Dojo API v2

Defect Dojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

The version of the OpenAPI document: 2.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from defectdojo_api_generated.api.endpoint_meta_import_api import EndpointMetaImportApi


class TestEndpointMetaImportApi(unittest.TestCase):
    """EndpointMetaImportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EndpointMetaImportApi()

    def tearDown(self) -> None:
        pass

    def test_endpoint_meta_import_create(self) -> None:
        """Test case for endpoint_meta_import_create"""
        pass


if __name__ == '__main__':
    unittest.main()
