# coding: utf-8

"""
Defect Dojo API v2

Defect Dojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

The version of the OpenAPI document: 2.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from defectdojo_api_generated.api.note_type_api import NoteTypeApi


class TestNoteTypeApi(unittest.TestCase):
    """NoteTypeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NoteTypeApi()

    def tearDown(self) -> None:
        pass

    def test_note_type_create(self) -> None:
        """Test case for note_type_create"""
        pass

    def test_note_type_delete_preview_list(self) -> None:
        """Test case for note_type_delete_preview_list"""
        pass

    def test_note_type_destroy(self) -> None:
        """Test case for note_type_destroy"""
        pass

    def test_note_type_list(self) -> None:
        """Test case for note_type_list"""
        pass

    def test_note_type_partial_update(self) -> None:
        """Test case for note_type_partial_update"""
        pass

    def test_note_type_retrieve(self) -> None:
        """Test case for note_type_retrieve"""
        pass

    def test_note_type_update(self) -> None:
        """Test case for note_type_update"""
        pass


if __name__ == '__main__':
    unittest.main()
