# coding: utf-8

"""
Defect Dojo API v2

Defect Dojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

The version of the OpenAPI document: 2.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from defectdojo_api_generated.api.product_types_api import ProductTypesApi


class TestProductTypesApi(unittest.TestCase):
    """ProductTypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductTypesApi()

    def tearDown(self) -> None:
        pass

    def test_product_types_create(self) -> None:
        """Test case for product_types_create"""
        pass

    def test_product_types_delete_preview_list(self) -> None:
        """Test case for product_types_delete_preview_list"""
        pass

    def test_product_types_destroy(self) -> None:
        """Test case for product_types_destroy"""
        pass

    def test_product_types_generate_report_create(self) -> None:
        """Test case for product_types_generate_report_create"""
        pass

    def test_product_types_list(self) -> None:
        """Test case for product_types_list"""
        pass

    def test_product_types_partial_update(self) -> None:
        """Test case for product_types_partial_update"""
        pass

    def test_product_types_retrieve(self) -> None:
        """Test case for product_types_retrieve"""
        pass

    def test_product_types_update(self) -> None:
        """Test case for product_types_update"""
        pass


if __name__ == '__main__':
    unittest.main()
