from dlubal.api.common import common_pb2 as _common_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class LineHingeTranslationalReleaseUXNonlinearity(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_NONE: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FAILURE_ALL_IF_NEGATIVE: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FAILURE_ALL_IF_POSITIVE: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FAILURE_IF_NEGATIVE: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FAILURE_IF_POSITIVE: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FORCE_MOMENT_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_2: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_PLUS_2: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_2: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_PARTIAL_ACTIVITY: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_STIFFNESS_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUXNonlinearity]

class LineHingeTranslationalReleaseUYNonlinearity(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_NONE: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FAILURE_ALL_IF_NEGATIVE: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FAILURE_ALL_IF_POSITIVE: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FAILURE_IF_NEGATIVE: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FAILURE_IF_POSITIVE: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FORCE_MOMENT_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FRICTION_DIRECTION_1: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_2: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_PLUS_2: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FRICTION_DIRECTION_2: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_PARTIAL_ACTIVITY: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_STIFFNESS_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUYNonlinearity]

class LineHingeTranslationalReleaseUZNonlinearity(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_NONE: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FAILURE_ALL_IF_NEGATIVE: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FAILURE_ALL_IF_POSITIVE: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FAILURE_IF_NEGATIVE: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FAILURE_IF_POSITIVE: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FORCE_MOMENT_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FRICTION_DIRECTION_1: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_2: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_PLUS_2: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FRICTION_DIRECTION_2: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_PARTIAL_ACTIVITY: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]
    LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_STIFFNESS_DIAGRAM: _ClassVar[LineHingeTranslationalReleaseUZNonlinearity]

class LineHingeRotationalReleasePhiXNonlinearity(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_NONE: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_DIAGRAM: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FAILURE_ALL_IF_NEGATIVE: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FAILURE_ALL_IF_POSITIVE: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FAILURE_IF_NEGATIVE: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FAILURE_IF_POSITIVE: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FORCE_MOMENT_DIAGRAM: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_2: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_PLUS_2: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_2: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_PARTIAL_ACTIVITY: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]
    LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_STIFFNESS_DIAGRAM: _ClassVar[LineHingeRotationalReleasePhiXNonlinearity]

class LineHingePartialActivityAlongXNegativeType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: _ClassVar[LineHingePartialActivityAlongXNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongXNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: _ClassVar[LineHingePartialActivityAlongXNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: _ClassVar[LineHingePartialActivityAlongXNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongXNegativeType]

class LineHingePartialActivityAlongXPositiveType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: _ClassVar[LineHingePartialActivityAlongXPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongXPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: _ClassVar[LineHingePartialActivityAlongXPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: _ClassVar[LineHingePartialActivityAlongXPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongXPositiveType]

class LineHingePartialActivityAlongYNegativeType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: _ClassVar[LineHingePartialActivityAlongYNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongYNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: _ClassVar[LineHingePartialActivityAlongYNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: _ClassVar[LineHingePartialActivityAlongYNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongYNegativeType]

class LineHingePartialActivityAlongYPositiveType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: _ClassVar[LineHingePartialActivityAlongYPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongYPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: _ClassVar[LineHingePartialActivityAlongYPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: _ClassVar[LineHingePartialActivityAlongYPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongYPositiveType]

class LineHingePartialActivityAlongZNegativeType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: _ClassVar[LineHingePartialActivityAlongZNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongZNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: _ClassVar[LineHingePartialActivityAlongZNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: _ClassVar[LineHingePartialActivityAlongZNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongZNegativeType]

class LineHingePartialActivityAlongZPositiveType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: _ClassVar[LineHingePartialActivityAlongZPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongZPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: _ClassVar[LineHingePartialActivityAlongZPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: _ClassVar[LineHingePartialActivityAlongZPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: _ClassVar[LineHingePartialActivityAlongZPositiveType]

class LineHingePartialActivityAroundXNegativeType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: _ClassVar[LineHingePartialActivityAroundXNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_MOMENT: _ClassVar[LineHingePartialActivityAroundXNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: _ClassVar[LineHingePartialActivityAroundXNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: _ClassVar[LineHingePartialActivityAroundXNegativeType]
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_MOMENT: _ClassVar[LineHingePartialActivityAroundXNegativeType]

class LineHingePartialActivityAroundXPositiveType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: _ClassVar[LineHingePartialActivityAroundXPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_MOMENT: _ClassVar[LineHingePartialActivityAroundXPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: _ClassVar[LineHingePartialActivityAroundXPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: _ClassVar[LineHingePartialActivityAroundXPositiveType]
    LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_MOMENT: _ClassVar[LineHingePartialActivityAroundXPositiveType]

class LineHingeDiagramAlongXStart(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_DIAGRAM_ALONG_X_START_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeDiagramAlongXStart]
    LINE_HINGE_DIAGRAM_ALONG_X_START_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeDiagramAlongXStart]
    LINE_HINGE_DIAGRAM_ALONG_X_START_DIAGRAM_ENDING_TYPE_STOP: _ClassVar[LineHingeDiagramAlongXStart]
    LINE_HINGE_DIAGRAM_ALONG_X_START_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeDiagramAlongXStart]

class LineHingeDiagramAlongYStart(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_DIAGRAM_ALONG_Y_START_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeDiagramAlongYStart]
    LINE_HINGE_DIAGRAM_ALONG_Y_START_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeDiagramAlongYStart]
    LINE_HINGE_DIAGRAM_ALONG_Y_START_DIAGRAM_ENDING_TYPE_STOP: _ClassVar[LineHingeDiagramAlongYStart]
    LINE_HINGE_DIAGRAM_ALONG_Y_START_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeDiagramAlongYStart]

class LineHingeDiagramAlongZStart(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_DIAGRAM_ALONG_Z_START_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeDiagramAlongZStart]
    LINE_HINGE_DIAGRAM_ALONG_Z_START_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeDiagramAlongZStart]
    LINE_HINGE_DIAGRAM_ALONG_Z_START_DIAGRAM_ENDING_TYPE_STOP: _ClassVar[LineHingeDiagramAlongZStart]
    LINE_HINGE_DIAGRAM_ALONG_Z_START_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeDiagramAlongZStart]

class LineHingeDiagramAroundXStart(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_DIAGRAM_AROUND_X_START_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeDiagramAroundXStart]
    LINE_HINGE_DIAGRAM_AROUND_X_START_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeDiagramAroundXStart]
    LINE_HINGE_DIAGRAM_AROUND_X_START_DIAGRAM_ENDING_TYPE_STOP: _ClassVar[LineHingeDiagramAroundXStart]
    LINE_HINGE_DIAGRAM_AROUND_X_START_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeDiagramAroundXStart]

class LineHingeDiagramAlongXEnd(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_DIAGRAM_ALONG_X_END_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeDiagramAlongXEnd]
    LINE_HINGE_DIAGRAM_ALONG_X_END_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeDiagramAlongXEnd]
    LINE_HINGE_DIAGRAM_ALONG_X_END_DIAGRAM_ENDING_TYPE_STOP: _ClassVar[LineHingeDiagramAlongXEnd]
    LINE_HINGE_DIAGRAM_ALONG_X_END_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeDiagramAlongXEnd]

class LineHingeDiagramAlongYEnd(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_DIAGRAM_ALONG_Y_END_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeDiagramAlongYEnd]
    LINE_HINGE_DIAGRAM_ALONG_Y_END_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeDiagramAlongYEnd]
    LINE_HINGE_DIAGRAM_ALONG_Y_END_DIAGRAM_ENDING_TYPE_STOP: _ClassVar[LineHingeDiagramAlongYEnd]
    LINE_HINGE_DIAGRAM_ALONG_Y_END_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeDiagramAlongYEnd]

class LineHingeDiagramAlongZEnd(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_DIAGRAM_ALONG_Z_END_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeDiagramAlongZEnd]
    LINE_HINGE_DIAGRAM_ALONG_Z_END_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeDiagramAlongZEnd]
    LINE_HINGE_DIAGRAM_ALONG_Z_END_DIAGRAM_ENDING_TYPE_STOP: _ClassVar[LineHingeDiagramAlongZEnd]
    LINE_HINGE_DIAGRAM_ALONG_Z_END_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeDiagramAlongZEnd]

class LineHingeDiagramAroundXEnd(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_DIAGRAM_AROUND_X_END_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeDiagramAroundXEnd]
    LINE_HINGE_DIAGRAM_AROUND_X_END_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeDiagramAroundXEnd]
    LINE_HINGE_DIAGRAM_AROUND_X_END_DIAGRAM_ENDING_TYPE_STOP: _ClassVar[LineHingeDiagramAroundXEnd]
    LINE_HINGE_DIAGRAM_AROUND_X_END_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeDiagramAroundXEnd]

class LineHingeForceMomentDiagramAroundXStart(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_START_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeForceMomentDiagramAroundXStart]
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_START_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeForceMomentDiagramAroundXStart]
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_START_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeForceMomentDiagramAroundXStart]

class LineHingeForceMomentDiagramAroundXEnd(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_END_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_FAILURE: _ClassVar[LineHingeForceMomentDiagramAroundXEnd]
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_END_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_CONTINUOUS: _ClassVar[LineHingeForceMomentDiagramAroundXEnd]
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_END_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_YIELDING: _ClassVar[LineHingeForceMomentDiagramAroundXEnd]

class LineHingeForceMomentDiagramAroundXDependsOn(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_DEPENDS_ON_FORCE_MOMENT_DIAGRAM_DEPENDS_ON_N: _ClassVar[LineHingeForceMomentDiagramAroundXDependsOn]
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_DEPENDS_ON_FORCE_MOMENT_DIAGRAM_DEPENDS_ON_VY: _ClassVar[LineHingeForceMomentDiagramAroundXDependsOn]
    LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_DEPENDS_ON_FORCE_MOMENT_DIAGRAM_DEPENDS_ON_VZ: _ClassVar[LineHingeForceMomentDiagramAroundXDependsOn]
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_NONE: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_DIAGRAM: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FAILURE_ALL_IF_NEGATIVE: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FAILURE_ALL_IF_POSITIVE: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FAILURE_IF_NEGATIVE: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FAILURE_IF_POSITIVE: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FORCE_MOMENT_DIAGRAM: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_2: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_PLUS_2: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_2: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_PARTIAL_ACTIVITY: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_TYPE_STIFFNESS_DIAGRAM: LineHingeTranslationalReleaseUXNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_NONE: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_DIAGRAM: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FAILURE_ALL_IF_NEGATIVE: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FAILURE_ALL_IF_POSITIVE: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FAILURE_IF_NEGATIVE: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FAILURE_IF_POSITIVE: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FORCE_MOMENT_DIAGRAM: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FRICTION_DIRECTION_1: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_2: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_PLUS_2: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_FRICTION_DIRECTION_2: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_PARTIAL_ACTIVITY: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_TYPE_STIFFNESS_DIAGRAM: LineHingeTranslationalReleaseUYNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_NONE: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_DIAGRAM: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FAILURE_ALL_IF_NEGATIVE: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FAILURE_ALL_IF_POSITIVE: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FAILURE_IF_NEGATIVE: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FAILURE_IF_POSITIVE: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FORCE_MOMENT_DIAGRAM: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FRICTION_DIRECTION_1: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_2: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_PLUS_2: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_FRICTION_DIRECTION_2: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_PARTIAL_ACTIVITY: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_TYPE_STIFFNESS_DIAGRAM: LineHingeTranslationalReleaseUZNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_NONE: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_DIAGRAM: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FAILURE_ALL_IF_NEGATIVE: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FAILURE_ALL_IF_POSITIVE: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FAILURE_IF_NEGATIVE: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FAILURE_IF_POSITIVE: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FORCE_MOMENT_DIAGRAM: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_2: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_1_PLUS_2: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_FRICTION_DIRECTION_2: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_PARTIAL_ACTIVITY: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_TYPE_STIFFNESS_DIAGRAM: LineHingeRotationalReleasePhiXNonlinearity
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: LineHingePartialActivityAlongXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: LineHingePartialActivityAlongXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: LineHingePartialActivityAlongXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: LineHingePartialActivityAlongXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: LineHingePartialActivityAlongXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: LineHingePartialActivityAlongXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: LineHingePartialActivityAlongXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: LineHingePartialActivityAlongXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: LineHingePartialActivityAlongXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: LineHingePartialActivityAlongXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: LineHingePartialActivityAlongYNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: LineHingePartialActivityAlongYNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: LineHingePartialActivityAlongYNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: LineHingePartialActivityAlongYNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: LineHingePartialActivityAlongYNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: LineHingePartialActivityAlongYPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: LineHingePartialActivityAlongYPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: LineHingePartialActivityAlongYPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: LineHingePartialActivityAlongYPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: LineHingePartialActivityAlongYPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: LineHingePartialActivityAlongZNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: LineHingePartialActivityAlongZNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: LineHingePartialActivityAlongZNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: LineHingePartialActivityAlongZNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: LineHingePartialActivityAlongZNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: LineHingePartialActivityAlongZPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_FORCE: LineHingePartialActivityAlongZPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: LineHingePartialActivityAlongZPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: LineHingePartialActivityAlongZPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_FORCE: LineHingePartialActivityAlongZPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: LineHingePartialActivityAroundXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_MOMENT: LineHingePartialActivityAroundXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: LineHingePartialActivityAroundXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: LineHingePartialActivityAroundXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_MOMENT: LineHingePartialActivityAroundXNegativeType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_COMPLETE: LineHingePartialActivityAroundXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FAILURE_FROM_MOMENT: LineHingePartialActivityAroundXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_FIXED: LineHingePartialActivityAroundXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_INEFFECTIVNESS: LineHingePartialActivityAroundXPositiveType
LINE_HINGE_PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_PARTIAL_ACTIVITY_TYPE_YIELDING_FROM_MOMENT: LineHingePartialActivityAroundXPositiveType
LINE_HINGE_DIAGRAM_ALONG_X_START_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeDiagramAlongXStart
LINE_HINGE_DIAGRAM_ALONG_X_START_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeDiagramAlongXStart
LINE_HINGE_DIAGRAM_ALONG_X_START_DIAGRAM_ENDING_TYPE_STOP: LineHingeDiagramAlongXStart
LINE_HINGE_DIAGRAM_ALONG_X_START_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeDiagramAlongXStart
LINE_HINGE_DIAGRAM_ALONG_Y_START_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeDiagramAlongYStart
LINE_HINGE_DIAGRAM_ALONG_Y_START_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeDiagramAlongYStart
LINE_HINGE_DIAGRAM_ALONG_Y_START_DIAGRAM_ENDING_TYPE_STOP: LineHingeDiagramAlongYStart
LINE_HINGE_DIAGRAM_ALONG_Y_START_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeDiagramAlongYStart
LINE_HINGE_DIAGRAM_ALONG_Z_START_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeDiagramAlongZStart
LINE_HINGE_DIAGRAM_ALONG_Z_START_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeDiagramAlongZStart
LINE_HINGE_DIAGRAM_ALONG_Z_START_DIAGRAM_ENDING_TYPE_STOP: LineHingeDiagramAlongZStart
LINE_HINGE_DIAGRAM_ALONG_Z_START_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeDiagramAlongZStart
LINE_HINGE_DIAGRAM_AROUND_X_START_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeDiagramAroundXStart
LINE_HINGE_DIAGRAM_AROUND_X_START_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeDiagramAroundXStart
LINE_HINGE_DIAGRAM_AROUND_X_START_DIAGRAM_ENDING_TYPE_STOP: LineHingeDiagramAroundXStart
LINE_HINGE_DIAGRAM_AROUND_X_START_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeDiagramAroundXStart
LINE_HINGE_DIAGRAM_ALONG_X_END_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeDiagramAlongXEnd
LINE_HINGE_DIAGRAM_ALONG_X_END_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeDiagramAlongXEnd
LINE_HINGE_DIAGRAM_ALONG_X_END_DIAGRAM_ENDING_TYPE_STOP: LineHingeDiagramAlongXEnd
LINE_HINGE_DIAGRAM_ALONG_X_END_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeDiagramAlongXEnd
LINE_HINGE_DIAGRAM_ALONG_Y_END_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeDiagramAlongYEnd
LINE_HINGE_DIAGRAM_ALONG_Y_END_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeDiagramAlongYEnd
LINE_HINGE_DIAGRAM_ALONG_Y_END_DIAGRAM_ENDING_TYPE_STOP: LineHingeDiagramAlongYEnd
LINE_HINGE_DIAGRAM_ALONG_Y_END_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeDiagramAlongYEnd
LINE_HINGE_DIAGRAM_ALONG_Z_END_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeDiagramAlongZEnd
LINE_HINGE_DIAGRAM_ALONG_Z_END_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeDiagramAlongZEnd
LINE_HINGE_DIAGRAM_ALONG_Z_END_DIAGRAM_ENDING_TYPE_STOP: LineHingeDiagramAlongZEnd
LINE_HINGE_DIAGRAM_ALONG_Z_END_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeDiagramAlongZEnd
LINE_HINGE_DIAGRAM_AROUND_X_END_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeDiagramAroundXEnd
LINE_HINGE_DIAGRAM_AROUND_X_END_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeDiagramAroundXEnd
LINE_HINGE_DIAGRAM_AROUND_X_END_DIAGRAM_ENDING_TYPE_STOP: LineHingeDiagramAroundXEnd
LINE_HINGE_DIAGRAM_AROUND_X_END_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeDiagramAroundXEnd
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_START_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeForceMomentDiagramAroundXStart
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_START_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeForceMomentDiagramAroundXStart
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_START_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeForceMomentDiagramAroundXStart
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_END_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_FAILURE: LineHingeForceMomentDiagramAroundXEnd
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_END_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_CONTINUOUS: LineHingeForceMomentDiagramAroundXEnd
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_END_FORCE_MOMENT_DIAGRAM_ENDING_TYPE_YIELDING: LineHingeForceMomentDiagramAroundXEnd
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_DEPENDS_ON_FORCE_MOMENT_DIAGRAM_DEPENDS_ON_N: LineHingeForceMomentDiagramAroundXDependsOn
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_DEPENDS_ON_FORCE_MOMENT_DIAGRAM_DEPENDS_ON_VY: LineHingeForceMomentDiagramAroundXDependsOn
LINE_HINGE_FORCE_MOMENT_DIAGRAM_AROUND_X_DEPENDS_ON_FORCE_MOMENT_DIAGRAM_DEPENDS_ON_VZ: LineHingeForceMomentDiagramAroundXDependsOn

class LineHinge(_message.Message):
    __slots__ = ("no", "user_defined_name_enabled", "name", "assigned_to", "translational_release_u_x", "translational_release_u_x_nonlinearity", "translational_release_u_y", "translational_release_u_y_nonlinearity", "translational_release_u_z", "translational_release_u_z_nonlinearity", "rotational_release_phi_x", "rotational_release_phi_x_nonlinearity", "partial_activity_along_x_negative_type", "partial_activity_along_x_positive_type", "partial_activity_along_y_negative_type", "partial_activity_along_y_positive_type", "partial_activity_along_z_negative_type", "partial_activity_along_z_positive_type", "partial_activity_around_x_negative_type", "partial_activity_around_x_positive_type", "partial_activity_along_x_negative_displacement", "partial_activity_along_x_positive_displacement", "partial_activity_along_y_negative_displacement", "partial_activity_along_y_positive_displacement", "partial_activity_along_z_negative_displacement", "partial_activity_along_z_positive_displacement", "partial_activity_around_x_negative_moment", "partial_activity_around_x_positive_moment", "partial_activity_along_x_negative_force", "partial_activity_along_x_positive_force", "partial_activity_along_y_negative_force", "partial_activity_along_y_positive_force", "partial_activity_along_z_negative_force", "partial_activity_along_z_positive_force", "partial_activity_around_x_negative_rotation", "partial_activity_around_x_positive_rotation", "partial_activity_along_x_negative_slippage", "partial_activity_along_x_positive_slippage", "partial_activity_along_y_negative_slippage", "partial_activity_along_y_positive_slippage", "partial_activity_along_z_negative_slippage", "partial_activity_along_z_positive_slippage", "partial_activity_around_x_negative_slippage", "partial_activity_around_x_positive_slippage", "diagram_along_x_symmetric", "diagram_along_y_symmetric", "diagram_along_z_symmetric", "diagram_around_x_symmetric", "diagram_along_x_is_sorted", "diagram_along_y_is_sorted", "diagram_along_z_is_sorted", "diagram_around_x_is_sorted", "diagram_along_x_table", "diagram_along_y_table", "diagram_along_z_table", "diagram_around_x_table", "diagram_along_x_start", "diagram_along_y_start", "diagram_along_z_start", "diagram_around_x_start", "diagram_along_x_end", "diagram_along_y_end", "diagram_along_z_end", "diagram_around_x_end", "diagram_along_x_ac_yield_minus", "diagram_along_y_ac_yield_minus", "diagram_along_z_ac_yield_minus", "diagram_around_x_ac_yield_minus", "diagram_along_x_ac_yield_plus", "diagram_along_y_ac_yield_plus", "diagram_along_z_ac_yield_plus", "diagram_around_x_ac_yield_plus", "diagram_along_x_acceptance_criteria_active", "diagram_along_y_acceptance_criteria_active", "diagram_along_z_acceptance_criteria_active", "diagram_around_x_acceptance_criteria_active", "diagram_along_x_minus_color_one", "diagram_along_y_minus_color_one", "diagram_along_z_minus_color_one", "diagram_around_x_minus_color_one", "diagram_along_x_minus_color_two", "diagram_along_y_minus_color_two", "diagram_along_z_minus_color_two", "diagram_around_x_minus_color_two", "diagram_along_x_plus_color_one", "diagram_along_y_plus_color_one", "diagram_along_z_plus_color_one", "diagram_around_x_plus_color_one", "diagram_along_x_plus_color_two", "diagram_along_y_plus_color_two", "diagram_along_z_plus_color_two", "diagram_around_x_plus_color_two", "diagram_along_x_color_table", "diagram_along_y_color_table", "diagram_along_z_color_table", "diagram_around_x_color_table", "force_moment_diagram_around_x_table", "force_moment_diagram_around_x_symmetric", "force_moment_diagram_around_x_is_sorted", "force_moment_diagram_around_x_start", "force_moment_diagram_around_x_end", "force_moment_diagram_around_x_depends_on", "slab_wall_connection", "slab_wall_connection_offset", "slab_wall_with_slab_edge_block", "slab_edge_block_width", "generated_line_hinges", "has_released_rotations_perpendicular_to_axis", "comment", "is_generated", "generating_object_info", "id_for_export_import", "metadata_for_export_import")
    NO_FIELD_NUMBER: _ClassVar[int]
    USER_DEFINED_NAME_ENABLED_FIELD_NUMBER: _ClassVar[int]
    NAME_FIELD_NUMBER: _ClassVar[int]
    ASSIGNED_TO_FIELD_NUMBER: _ClassVar[int]
    TRANSLATIONAL_RELEASE_U_X_FIELD_NUMBER: _ClassVar[int]
    TRANSLATIONAL_RELEASE_U_X_NONLINEARITY_FIELD_NUMBER: _ClassVar[int]
    TRANSLATIONAL_RELEASE_U_Y_FIELD_NUMBER: _ClassVar[int]
    TRANSLATIONAL_RELEASE_U_Y_NONLINEARITY_FIELD_NUMBER: _ClassVar[int]
    TRANSLATIONAL_RELEASE_U_Z_FIELD_NUMBER: _ClassVar[int]
    TRANSLATIONAL_RELEASE_U_Z_NONLINEARITY_FIELD_NUMBER: _ClassVar[int]
    ROTATIONAL_RELEASE_PHI_X_FIELD_NUMBER: _ClassVar[int]
    ROTATIONAL_RELEASE_PHI_X_NONLINEARITY_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_X_POSITIVE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_AROUND_X_POSITIVE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_X_POSITIVE_DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_MOMENT_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_AROUND_X_POSITIVE_MOMENT_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_FORCE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_X_POSITIVE_FORCE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_FORCE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_FORCE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_FORCE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_FORCE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_ROTATION_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_AROUND_X_POSITIVE_ROTATION_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_X_NEGATIVE_SLIPPAGE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_X_POSITIVE_SLIPPAGE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Y_NEGATIVE_SLIPPAGE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Y_POSITIVE_SLIPPAGE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Z_NEGATIVE_SLIPPAGE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_ALONG_Z_POSITIVE_SLIPPAGE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_AROUND_X_NEGATIVE_SLIPPAGE_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_ACTIVITY_AROUND_X_POSITIVE_SLIPPAGE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_SYMMETRIC_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_SYMMETRIC_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_SYMMETRIC_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_SYMMETRIC_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_IS_SORTED_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_IS_SORTED_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_IS_SORTED_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_IS_SORTED_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_TABLE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_TABLE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_TABLE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_TABLE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_START_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_START_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_START_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_START_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_END_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_END_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_END_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_END_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_AC_YIELD_MINUS_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_AC_YIELD_MINUS_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_AC_YIELD_MINUS_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_AC_YIELD_MINUS_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_AC_YIELD_PLUS_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_AC_YIELD_PLUS_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_AC_YIELD_PLUS_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_AC_YIELD_PLUS_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_ACCEPTANCE_CRITERIA_ACTIVE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_ACCEPTANCE_CRITERIA_ACTIVE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_ACCEPTANCE_CRITERIA_ACTIVE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_ACCEPTANCE_CRITERIA_ACTIVE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_MINUS_COLOR_ONE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_MINUS_COLOR_ONE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_MINUS_COLOR_ONE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_MINUS_COLOR_ONE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_MINUS_COLOR_TWO_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_MINUS_COLOR_TWO_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_MINUS_COLOR_TWO_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_MINUS_COLOR_TWO_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_PLUS_COLOR_ONE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_PLUS_COLOR_ONE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_PLUS_COLOR_ONE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_PLUS_COLOR_ONE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_PLUS_COLOR_TWO_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_PLUS_COLOR_TWO_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_PLUS_COLOR_TWO_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_PLUS_COLOR_TWO_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_X_COLOR_TABLE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Y_COLOR_TABLE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_ALONG_Z_COLOR_TABLE_FIELD_NUMBER: _ClassVar[int]
    DIAGRAM_AROUND_X_COLOR_TABLE_FIELD_NUMBER: _ClassVar[int]
    FORCE_MOMENT_DIAGRAM_AROUND_X_TABLE_FIELD_NUMBER: _ClassVar[int]
    FORCE_MOMENT_DIAGRAM_AROUND_X_SYMMETRIC_FIELD_NUMBER: _ClassVar[int]
    FORCE_MOMENT_DIAGRAM_AROUND_X_IS_SORTED_FIELD_NUMBER: _ClassVar[int]
    FORCE_MOMENT_DIAGRAM_AROUND_X_START_FIELD_NUMBER: _ClassVar[int]
    FORCE_MOMENT_DIAGRAM_AROUND_X_END_FIELD_NUMBER: _ClassVar[int]
    FORCE_MOMENT_DIAGRAM_AROUND_X_DEPENDS_ON_FIELD_NUMBER: _ClassVar[int]
    SLAB_WALL_CONNECTION_FIELD_NUMBER: _ClassVar[int]
    SLAB_WALL_CONNECTION_OFFSET_FIELD_NUMBER: _ClassVar[int]
    SLAB_WALL_WITH_SLAB_EDGE_BLOCK_FIELD_NUMBER: _ClassVar[int]
    SLAB_EDGE_BLOCK_WIDTH_FIELD_NUMBER: _ClassVar[int]
    GENERATED_LINE_HINGES_FIELD_NUMBER: _ClassVar[int]
    HAS_RELEASED_ROTATIONS_PERPENDICULAR_TO_AXIS_FIELD_NUMBER: _ClassVar[int]
    COMMENT_FIELD_NUMBER: _ClassVar[int]
    IS_GENERATED_FIELD_NUMBER: _ClassVar[int]
    GENERATING_OBJECT_INFO_FIELD_NUMBER: _ClassVar[int]
    ID_FOR_EXPORT_IMPORT_FIELD_NUMBER: _ClassVar[int]
    METADATA_FOR_EXPORT_IMPORT_FIELD_NUMBER: _ClassVar[int]
    no: int
    user_defined_name_enabled: bool
    name: str
    assigned_to: str
    translational_release_u_x: float
    translational_release_u_x_nonlinearity: LineHingeTranslationalReleaseUXNonlinearity
    translational_release_u_y: float
    translational_release_u_y_nonlinearity: LineHingeTranslationalReleaseUYNonlinearity
    translational_release_u_z: float
    translational_release_u_z_nonlinearity: LineHingeTranslationalReleaseUZNonlinearity
    rotational_release_phi_x: float
    rotational_release_phi_x_nonlinearity: LineHingeRotationalReleasePhiXNonlinearity
    partial_activity_along_x_negative_type: LineHingePartialActivityAlongXNegativeType
    partial_activity_along_x_positive_type: LineHingePartialActivityAlongXPositiveType
    partial_activity_along_y_negative_type: LineHingePartialActivityAlongYNegativeType
    partial_activity_along_y_positive_type: LineHingePartialActivityAlongYPositiveType
    partial_activity_along_z_negative_type: LineHingePartialActivityAlongZNegativeType
    partial_activity_along_z_positive_type: LineHingePartialActivityAlongZPositiveType
    partial_activity_around_x_negative_type: LineHingePartialActivityAroundXNegativeType
    partial_activity_around_x_positive_type: LineHingePartialActivityAroundXPositiveType
    partial_activity_along_x_negative_displacement: float
    partial_activity_along_x_positive_displacement: float
    partial_activity_along_y_negative_displacement: float
    partial_activity_along_y_positive_displacement: float
    partial_activity_along_z_negative_displacement: float
    partial_activity_along_z_positive_displacement: float
    partial_activity_around_x_negative_moment: float
    partial_activity_around_x_positive_moment: float
    partial_activity_along_x_negative_force: float
    partial_activity_along_x_positive_force: float
    partial_activity_along_y_negative_force: float
    partial_activity_along_y_positive_force: float
    partial_activity_along_z_negative_force: float
    partial_activity_along_z_positive_force: float
    partial_activity_around_x_negative_rotation: float
    partial_activity_around_x_positive_rotation: float
    partial_activity_along_x_negative_slippage: float
    partial_activity_along_x_positive_slippage: float
    partial_activity_along_y_negative_slippage: float
    partial_activity_along_y_positive_slippage: float
    partial_activity_along_z_negative_slippage: float
    partial_activity_along_z_positive_slippage: float
    partial_activity_around_x_negative_slippage: float
    partial_activity_around_x_positive_slippage: float
    diagram_along_x_symmetric: bool
    diagram_along_y_symmetric: bool
    diagram_along_z_symmetric: bool
    diagram_around_x_symmetric: bool
    diagram_along_x_is_sorted: bool
    diagram_along_y_is_sorted: bool
    diagram_along_z_is_sorted: bool
    diagram_around_x_is_sorted: bool
    diagram_along_x_table: LineHingeDiagramAlongXTable
    diagram_along_y_table: LineHingeDiagramAlongYTable
    diagram_along_z_table: LineHingeDiagramAlongZTable
    diagram_around_x_table: LineHingeDiagramAroundXTable
    diagram_along_x_start: LineHingeDiagramAlongXStart
    diagram_along_y_start: LineHingeDiagramAlongYStart
    diagram_along_z_start: LineHingeDiagramAlongZStart
    diagram_around_x_start: LineHingeDiagramAroundXStart
    diagram_along_x_end: LineHingeDiagramAlongXEnd
    diagram_along_y_end: LineHingeDiagramAlongYEnd
    diagram_along_z_end: LineHingeDiagramAlongZEnd
    diagram_around_x_end: LineHingeDiagramAroundXEnd
    diagram_along_x_ac_yield_minus: float
    diagram_along_y_ac_yield_minus: float
    diagram_along_z_ac_yield_minus: float
    diagram_around_x_ac_yield_minus: float
    diagram_along_x_ac_yield_plus: float
    diagram_along_y_ac_yield_plus: float
    diagram_along_z_ac_yield_plus: float
    diagram_around_x_ac_yield_plus: float
    diagram_along_x_acceptance_criteria_active: bool
    diagram_along_y_acceptance_criteria_active: bool
    diagram_along_z_acceptance_criteria_active: bool
    diagram_around_x_acceptance_criteria_active: bool
    diagram_along_x_minus_color_one: _common_pb2.Color
    diagram_along_y_minus_color_one: _common_pb2.Color
    diagram_along_z_minus_color_one: _common_pb2.Color
    diagram_around_x_minus_color_one: _common_pb2.Color
    diagram_along_x_minus_color_two: _common_pb2.Color
    diagram_along_y_minus_color_two: _common_pb2.Color
    diagram_along_z_minus_color_two: _common_pb2.Color
    diagram_around_x_minus_color_two: _common_pb2.Color
    diagram_along_x_plus_color_one: _common_pb2.Color
    diagram_along_y_plus_color_one: _common_pb2.Color
    diagram_along_z_plus_color_one: _common_pb2.Color
    diagram_around_x_plus_color_one: _common_pb2.Color
    diagram_along_x_plus_color_two: _common_pb2.Color
    diagram_along_y_plus_color_two: _common_pb2.Color
    diagram_along_z_plus_color_two: _common_pb2.Color
    diagram_around_x_plus_color_two: _common_pb2.Color
    diagram_along_x_color_table: LineHingeDiagramAlongXColorTable
    diagram_along_y_color_table: LineHingeDiagramAlongYColorTable
    diagram_along_z_color_table: LineHingeDiagramAlongZColorTable
    diagram_around_x_color_table: LineHingeDiagramAroundXColorTable
    force_moment_diagram_around_x_table: LineHingeForceMomentDiagramAroundXTable
    force_moment_diagram_around_x_symmetric: bool
    force_moment_diagram_around_x_is_sorted: bool
    force_moment_diagram_around_x_start: LineHingeForceMomentDiagramAroundXStart
    force_moment_diagram_around_x_end: LineHingeForceMomentDiagramAroundXEnd
    force_moment_diagram_around_x_depends_on: LineHingeForceMomentDiagramAroundXDependsOn
    slab_wall_connection: bool
    slab_wall_connection_offset: float
    slab_wall_with_slab_edge_block: bool
    slab_edge_block_width: float
    generated_line_hinges: LineHingeGeneratedLineHingesTable
    has_released_rotations_perpendicular_to_axis: bool
    comment: str
    is_generated: bool
    generating_object_info: str
    id_for_export_import: str
    metadata_for_export_import: str
    def __init__(self, no: _Optional[int] = ..., user_defined_name_enabled: bool = ..., name: _Optional[str] = ..., assigned_to: _Optional[str] = ..., translational_release_u_x: _Optional[float] = ..., translational_release_u_x_nonlinearity: _Optional[_Union[LineHingeTranslationalReleaseUXNonlinearity, str]] = ..., translational_release_u_y: _Optional[float] = ..., translational_release_u_y_nonlinearity: _Optional[_Union[LineHingeTranslationalReleaseUYNonlinearity, str]] = ..., translational_release_u_z: _Optional[float] = ..., translational_release_u_z_nonlinearity: _Optional[_Union[LineHingeTranslationalReleaseUZNonlinearity, str]] = ..., rotational_release_phi_x: _Optional[float] = ..., rotational_release_phi_x_nonlinearity: _Optional[_Union[LineHingeRotationalReleasePhiXNonlinearity, str]] = ..., partial_activity_along_x_negative_type: _Optional[_Union[LineHingePartialActivityAlongXNegativeType, str]] = ..., partial_activity_along_x_positive_type: _Optional[_Union[LineHingePartialActivityAlongXPositiveType, str]] = ..., partial_activity_along_y_negative_type: _Optional[_Union[LineHingePartialActivityAlongYNegativeType, str]] = ..., partial_activity_along_y_positive_type: _Optional[_Union[LineHingePartialActivityAlongYPositiveType, str]] = ..., partial_activity_along_z_negative_type: _Optional[_Union[LineHingePartialActivityAlongZNegativeType, str]] = ..., partial_activity_along_z_positive_type: _Optional[_Union[LineHingePartialActivityAlongZPositiveType, str]] = ..., partial_activity_around_x_negative_type: _Optional[_Union[LineHingePartialActivityAroundXNegativeType, str]] = ..., partial_activity_around_x_positive_type: _Optional[_Union[LineHingePartialActivityAroundXPositiveType, str]] = ..., partial_activity_along_x_negative_displacement: _Optional[float] = ..., partial_activity_along_x_positive_displacement: _Optional[float] = ..., partial_activity_along_y_negative_displacement: _Optional[float] = ..., partial_activity_along_y_positive_displacement: _Optional[float] = ..., partial_activity_along_z_negative_displacement: _Optional[float] = ..., partial_activity_along_z_positive_displacement: _Optional[float] = ..., partial_activity_around_x_negative_moment: _Optional[float] = ..., partial_activity_around_x_positive_moment: _Optional[float] = ..., partial_activity_along_x_negative_force: _Optional[float] = ..., partial_activity_along_x_positive_force: _Optional[float] = ..., partial_activity_along_y_negative_force: _Optional[float] = ..., partial_activity_along_y_positive_force: _Optional[float] = ..., partial_activity_along_z_negative_force: _Optional[float] = ..., partial_activity_along_z_positive_force: _Optional[float] = ..., partial_activity_around_x_negative_rotation: _Optional[float] = ..., partial_activity_around_x_positive_rotation: _Optional[float] = ..., partial_activity_along_x_negative_slippage: _Optional[float] = ..., partial_activity_along_x_positive_slippage: _Optional[float] = ..., partial_activity_along_y_negative_slippage: _Optional[float] = ..., partial_activity_along_y_positive_slippage: _Optional[float] = ..., partial_activity_along_z_negative_slippage: _Optional[float] = ..., partial_activity_along_z_positive_slippage: _Optional[float] = ..., partial_activity_around_x_negative_slippage: _Optional[float] = ..., partial_activity_around_x_positive_slippage: _Optional[float] = ..., diagram_along_x_symmetric: bool = ..., diagram_along_y_symmetric: bool = ..., diagram_along_z_symmetric: bool = ..., diagram_around_x_symmetric: bool = ..., diagram_along_x_is_sorted: bool = ..., diagram_along_y_is_sorted: bool = ..., diagram_along_z_is_sorted: bool = ..., diagram_around_x_is_sorted: bool = ..., diagram_along_x_table: _Optional[_Union[LineHingeDiagramAlongXTable, _Mapping]] = ..., diagram_along_y_table: _Optional[_Union[LineHingeDiagramAlongYTable, _Mapping]] = ..., diagram_along_z_table: _Optional[_Union[LineHingeDiagramAlongZTable, _Mapping]] = ..., diagram_around_x_table: _Optional[_Union[LineHingeDiagramAroundXTable, _Mapping]] = ..., diagram_along_x_start: _Optional[_Union[LineHingeDiagramAlongXStart, str]] = ..., diagram_along_y_start: _Optional[_Union[LineHingeDiagramAlongYStart, str]] = ..., diagram_along_z_start: _Optional[_Union[LineHingeDiagramAlongZStart, str]] = ..., diagram_around_x_start: _Optional[_Union[LineHingeDiagramAroundXStart, str]] = ..., diagram_along_x_end: _Optional[_Union[LineHingeDiagramAlongXEnd, str]] = ..., diagram_along_y_end: _Optional[_Union[LineHingeDiagramAlongYEnd, str]] = ..., diagram_along_z_end: _Optional[_Union[LineHingeDiagramAlongZEnd, str]] = ..., diagram_around_x_end: _Optional[_Union[LineHingeDiagramAroundXEnd, str]] = ..., diagram_along_x_ac_yield_minus: _Optional[float] = ..., diagram_along_y_ac_yield_minus: _Optional[float] = ..., diagram_along_z_ac_yield_minus: _Optional[float] = ..., diagram_around_x_ac_yield_minus: _Optional[float] = ..., diagram_along_x_ac_yield_plus: _Optional[float] = ..., diagram_along_y_ac_yield_plus: _Optional[float] = ..., diagram_along_z_ac_yield_plus: _Optional[float] = ..., diagram_around_x_ac_yield_plus: _Optional[float] = ..., diagram_along_x_acceptance_criteria_active: bool = ..., diagram_along_y_acceptance_criteria_active: bool = ..., diagram_along_z_acceptance_criteria_active: bool = ..., diagram_around_x_acceptance_criteria_active: bool = ..., diagram_along_x_minus_color_one: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_y_minus_color_one: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_z_minus_color_one: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_around_x_minus_color_one: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_x_minus_color_two: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_y_minus_color_two: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_z_minus_color_two: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_around_x_minus_color_two: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_x_plus_color_one: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_y_plus_color_one: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_z_plus_color_one: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_around_x_plus_color_one: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_x_plus_color_two: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_y_plus_color_two: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_z_plus_color_two: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_around_x_plus_color_two: _Optional[_Union[_common_pb2.Color, _Mapping]] = ..., diagram_along_x_color_table: _Optional[_Union[LineHingeDiagramAlongXColorTable, _Mapping]] = ..., diagram_along_y_color_table: _Optional[_Union[LineHingeDiagramAlongYColorTable, _Mapping]] = ..., diagram_along_z_color_table: _Optional[_Union[LineHingeDiagramAlongZColorTable, _Mapping]] = ..., diagram_around_x_color_table: _Optional[_Union[LineHingeDiagramAroundXColorTable, _Mapping]] = ..., force_moment_diagram_around_x_table: _Optional[_Union[LineHingeForceMomentDiagramAroundXTable, _Mapping]] = ..., force_moment_diagram_around_x_symmetric: bool = ..., force_moment_diagram_around_x_is_sorted: bool = ..., force_moment_diagram_around_x_start: _Optional[_Union[LineHingeForceMomentDiagramAroundXStart, str]] = ..., force_moment_diagram_around_x_end: _Optional[_Union[LineHingeForceMomentDiagramAroundXEnd, str]] = ..., force_moment_diagram_around_x_depends_on: _Optional[_Union[LineHingeForceMomentDiagramAroundXDependsOn, str]] = ..., slab_wall_connection: bool = ..., slab_wall_connection_offset: _Optional[float] = ..., slab_wall_with_slab_edge_block: bool = ..., slab_edge_block_width: _Optional[float] = ..., generated_line_hinges: _Optional[_Union[LineHingeGeneratedLineHingesTable, _Mapping]] = ..., has_released_rotations_perpendicular_to_axis: bool = ..., comment: _Optional[str] = ..., is_generated: bool = ..., generating_object_info: _Optional[str] = ..., id_for_export_import: _Optional[str] = ..., metadata_for_export_import: _Optional[str] = ...) -> None: ...

class LineHingeDiagramAlongXTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeDiagramAlongXTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeDiagramAlongXTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeDiagramAlongXTableRow(_message.Message):
    __slots__ = ("no", "description", "displacement", "force", "spring", "note")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    FORCE_FIELD_NUMBER: _ClassVar[int]
    SPRING_FIELD_NUMBER: _ClassVar[int]
    NOTE_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    displacement: float
    force: float
    spring: float
    note: str
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., displacement: _Optional[float] = ..., force: _Optional[float] = ..., spring: _Optional[float] = ..., note: _Optional[str] = ...) -> None: ...

class LineHingeDiagramAlongYTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeDiagramAlongYTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeDiagramAlongYTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeDiagramAlongYTableRow(_message.Message):
    __slots__ = ("no", "description", "displacement", "force", "spring", "note")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    FORCE_FIELD_NUMBER: _ClassVar[int]
    SPRING_FIELD_NUMBER: _ClassVar[int]
    NOTE_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    displacement: float
    force: float
    spring: float
    note: str
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., displacement: _Optional[float] = ..., force: _Optional[float] = ..., spring: _Optional[float] = ..., note: _Optional[str] = ...) -> None: ...

class LineHingeDiagramAlongZTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeDiagramAlongZTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeDiagramAlongZTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeDiagramAlongZTableRow(_message.Message):
    __slots__ = ("no", "description", "displacement", "force", "spring", "note")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    DISPLACEMENT_FIELD_NUMBER: _ClassVar[int]
    FORCE_FIELD_NUMBER: _ClassVar[int]
    SPRING_FIELD_NUMBER: _ClassVar[int]
    NOTE_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    displacement: float
    force: float
    spring: float
    note: str
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., displacement: _Optional[float] = ..., force: _Optional[float] = ..., spring: _Optional[float] = ..., note: _Optional[str] = ...) -> None: ...

class LineHingeDiagramAroundXTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeDiagramAroundXTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeDiagramAroundXTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeDiagramAroundXTableRow(_message.Message):
    __slots__ = ("no", "description", "rotation", "moment", "spring", "note")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    ROTATION_FIELD_NUMBER: _ClassVar[int]
    MOMENT_FIELD_NUMBER: _ClassVar[int]
    SPRING_FIELD_NUMBER: _ClassVar[int]
    NOTE_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    rotation: float
    moment: float
    spring: float
    note: str
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., rotation: _Optional[float] = ..., moment: _Optional[float] = ..., spring: _Optional[float] = ..., note: _Optional[str] = ...) -> None: ...

class LineHingeDiagramAlongXColorTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeDiagramAlongXColorTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeDiagramAlongXColorTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeDiagramAlongXColorTableRow(_message.Message):
    __slots__ = ("no", "description", "color")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    COLOR_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    color: _common_pb2.Color
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., color: _Optional[_Union[_common_pb2.Color, _Mapping]] = ...) -> None: ...

class LineHingeDiagramAlongYColorTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeDiagramAlongYColorTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeDiagramAlongYColorTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeDiagramAlongYColorTableRow(_message.Message):
    __slots__ = ("no", "description", "color")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    COLOR_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    color: _common_pb2.Color
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., color: _Optional[_Union[_common_pb2.Color, _Mapping]] = ...) -> None: ...

class LineHingeDiagramAlongZColorTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeDiagramAlongZColorTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeDiagramAlongZColorTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeDiagramAlongZColorTableRow(_message.Message):
    __slots__ = ("no", "description", "color")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    COLOR_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    color: _common_pb2.Color
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., color: _Optional[_Union[_common_pb2.Color, _Mapping]] = ...) -> None: ...

class LineHingeDiagramAroundXColorTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeDiagramAroundXColorTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeDiagramAroundXColorTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeDiagramAroundXColorTableRow(_message.Message):
    __slots__ = ("no", "description", "color")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    COLOR_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    color: _common_pb2.Color
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., color: _Optional[_Union[_common_pb2.Color, _Mapping]] = ...) -> None: ...

class LineHingeForceMomentDiagramAroundXTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeForceMomentDiagramAroundXTableRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeForceMomentDiagramAroundXTableRow, _Mapping]]] = ...) -> None: ...

class LineHingeForceMomentDiagramAroundXTableRow(_message.Message):
    __slots__ = ("no", "description", "force", "max_moment", "min_moment", "note")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    FORCE_FIELD_NUMBER: _ClassVar[int]
    MAX_MOMENT_FIELD_NUMBER: _ClassVar[int]
    MIN_MOMENT_FIELD_NUMBER: _ClassVar[int]
    NOTE_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    force: float
    max_moment: float
    min_moment: float
    note: str
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., force: _Optional[float] = ..., max_moment: _Optional[float] = ..., min_moment: _Optional[float] = ..., note: _Optional[str] = ...) -> None: ...

class LineHingeGeneratedLineHingesTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[LineHingeGeneratedLineHingesRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[LineHingeGeneratedLineHingesRow, _Mapping]]] = ...) -> None: ...

class LineHingeGeneratedLineHingesRow(_message.Message):
    __slots__ = ("no", "description", "generated_by", "generated_line_hinge")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    GENERATED_BY_FIELD_NUMBER: _ClassVar[int]
    GENERATED_LINE_HINGE_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    generated_by: int
    generated_line_hinge: int
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., generated_by: _Optional[int] = ..., generated_line_hinge: _Optional[int] = ...) -> None: ...
