DEFAULT_PYFILE = "__init__.py"
SYMBOL_NEW_LINE = "\n"
FILE_READ_MODE = "r"
FILE_WRITE_MODE = "w"
FILE_APPEND_MODE = "a"
FILE_ENCODING = "utf-8"
REGEX_IMPORT = r"^\s*(import |from )"
REGEX_NORMALIZED_TEXT = r"[-_\s]+"
