# coding: utf-8

"""
Defect Dojo API v2

Defect Dojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

The version of the OpenAPI document: 2.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from defectdojo_api_generated.models.endpoint_meta_importer import EndpointMetaImporter


class TestEndpointMetaImporter(unittest.TestCase):
    """EndpointMetaImporter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EndpointMetaImporter:
        """Test EndpointMetaImporter
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EndpointMetaImporter`
        """
        model = EndpointMetaImporter()
        if include_optional:
            return EndpointMetaImporter(
                file = '',
                create_endpoints = True,
                create_tags = True,
                create_dojo_meta = True,
                product_name = '',
                product = 56,
                product_id = 56
            )
        else:
            return EndpointMetaImporter(
                file = '',
                product_id = 56,
        )
        """

    def testEndpointMetaImporter(self):
        """Test EndpointMetaImporter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
