GLOTLID_MAPPING = {
    'aai': 'aa',  # Afar
    'afr': 'af',  # Afrikaans
    'amh': 'am',  # Amharic
    'arb': 'ar',  # Arabic
    'asm': 'as',  # Assamese
    'ava': 'av',  # Avaric
    'ayr': 'ay',  # Aymara
    'azj': 'az',  # Azerbaijani
    'bak': 'ba',  # Bashkir
    'bel': 'be',  # Belarusian
    'bem': 'zm',  # Bemba
    'ben': 'bn',  # Bengali
    'bho': 'bh',  # Bhojpuri
    'bis': 'bi',  # Bislama
    'bod': 'bo',  # Tibetan
    'bos': 'bs',  # Bosnian
    'bre': 'br',  # Breton
    'bug': 'bug', # Buginese
    'bul': 'bg',  # Bulgarian 
    'cat': 'ca',  # Catalan
    'ces': 'cs',  # Czech
    'cym': 'cy',  # Welsh
    'dan': 'da',  # Danish
    'deu': 'de',  # German
    'div': 'dv',  # Divehi
    'dzo': 'dz',  # Dzongkha
    'ell': 'el',  # Greek
    'eng': 'en',  # English
    'epo': 'eo',  # Esperanto
    'est': 'et',  # Estonian
    'eus': 'eu',  # Basque
    'fao': 'fo',  # Faroese
    'fas': 'fa',  # Persian
    'fin': 'fi',  # Finnish
    'fij': 'fj',  # Fijian
    'fra': 'fr',  # French
    'fry': 'fy',  # Western Frisian
    'gle': 'ga',  # Irish
    'gla': 'gd',  # Scottish Gaelic
    'glg': 'gl',  # Galician
    'guj': 'gu',  # Gujarati
    'hau': 'ha',  # Hausa
    'heb': 'he',  # Hebrew
    'hin': 'hi',  # Hindi
    'hrv': 'hr',  # Croatian
    'hun': 'hu',  # Hungarian
    'hye': 'hy',  # Armenian
    'ind': 'id',  # Indonesian
    'isl': 'is',  # Icelandic
    'ita': 'it',  # Italian
    'jpn': 'ja',  # Japanese
    'kat': 'ka',  # Georgian
    'kaz': 'kk',  # Kazakh
    'khm': 'km',  # Khmer
    'kir': 'ky',  # Kyrgyz
    'kor': 'ko',  # Korean
    'kur': 'ku',  # Kurdish
    'lao': 'lo',  # Lao
    'lat': 'la',  # Latin
    'lav': 'lv',  # Latvian
    'lit': 'lt',  # Lithuanian
    'ltz': 'lb',  # Luxembourgish
    'mal': 'ml',  # Malayalam
    'mar': 'mr',  # Marathi
    'mkd': 'mk',  # Macedonian
    'mlg': 'mg',  # Malagasy
    'mlt': 'mt',  # Maltese
    'mon': 'mn',  # Mongolian
    'mri': 'mi',  # Maori
    'msa': 'ms',  # Malay
    'mya': 'my',  # Burmese
    'nep': 'ne',  # Nepali
    'nld': 'nl',  # Dutch
    'nor': 'no',  # Norwegian
    'nya': 'ny',  # Chichewa
    'ori': 'or',  # Oriya
    'pan': 'pa',  # Punjabi
    'pol': 'pl',  # Polish
    'por': 'pt',  # Portuguese
    'pus': 'ps',  # Pashto
    'que': 'qu',  # Quechua
    'ron': 'ro',  # Romanian
    'rus': 'ru',  # Russian
    'san': 'sa',  # Sanskrit
    'sin': 'si',  # Sinhala
    'slk': 'sk',  # Slovak
    'slv': 'sl',  # Slovenian
    'sme': 'se',  # Northern Sami
    'sna': 'sn',  # Shona
    'som': 'so',  # Somali
    'spa': 'es',  # Spanish
    'sqi': 'sq',  # Albanian
    'srp': 'sr',  # Serbian
    'sun': 'su',  # Sundanese
    'swa': 'sw',  # Swahili
    'swe': 'sv',  # Swedish
    'tam': 'ta',  # Tamil
    'tel': 'te',  # Telugu
    'tgk': 'tg',  # Tajik
    'tha': 'th',  # Thai
    'tir': 'ti',  # Tigrinya
    'ton': 'to',  # Tonga
    'tur': 'tr',  # Turkish
    'uig': 'ug',  # Uyghur
    'ukr': 'uk',  # Ukrainian
    'urd': 'ur',  # Urdu
    'uzb': 'uz',  # Uzbek
    'vie': 'vi',  # Vietnamese
    'vol': 'vo',  # Volapük
    'xho': 'xh',  # Xhosa
    'yid': 'yi',  # Yiddish
    'yor': 'yo',  # Yoruba
    'zho': 'zh',  # Chinese
    'zul': 'zu'   # Zulu
}