from pydiful.interfaces.ServiceCollection import ServiceCollection as ServiceCollection
from pydiful.interfaces.ServiceProvider import ServiceProvider as ServiceProvider

class HostApplicationBuilder:
    service_collection: ServiceCollection
    service_provider: ServiceProvider
    def __init__(self) -> None: ...
    @classmethod
    def add_singleton(cls, abstract: type, concrete: type) -> None: ...
    @classmethod
    def add_scoped(cls, abstract: type, concrete: type) -> None: ...
    @classmethod
    def add_transient(cls, abstract: type, concrete: type) -> None: ...
    @classmethod
    def build(cls) -> None: ...

def inject(cls) -> None: ...
