# Generated by Django 2.2.19 on 2021-11-29 16:47
from django.db import (
    migrations,
)

import kinder.core.models


class Migration(migrations.Migration):
    dependencies = [
        ('smev3_v321', '0010_declarationportalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateclassifierrequest',
            name='data',
            field=kinder.core.models.RawJSONField(verbose_name='Данные запроса'),
        ),
    ]
