import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_94de85c1e5(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_fecc50656b():spartaqube_cli.list()
@app.command()
def sparta_cb5f68f253():spartaqube_cli.sparta_cb5f68f253()
@app.command()
def sparta_c351462137():print('Hello world!')
if __name__=='__main__':app()