from .kinematics import *
from .dynamics import *
from .electrostatics import *
from .friction_and_elasticy_forces import *
from .geometrical_optics import *
from .hydrostatics_aerostatics import *
from .thermodynamics import *
from .waves_and_oscillations import *
from .electricity_magnetism import *
from .other import *