
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-18T13:32:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "71ceaba53599a288de01e64e119e186aef822f49",
 "version": "1.33.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
