from __future__ import annotations

from typing import Any

def scatter(*args: Any, **kwargs: Any) -> None: ...
def plot(*args: Any, **kwargs: Any) -> None: ...
def savefig(*args: Any, **kwargs: Any) -> None: ...
def clf() -> None: ...
