# Generated by Django 5.0.9 on 2024-12-23 03:59

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=128)),
                ('deivce_error', models.CharField(blank=True, null=True)),
                ('deivce_type_error', models.CharField(blank=True, null=True)),
                ('deivce_role_error', models.CharField(blank=True, null=True)),
                ('rack_error', models.CharField(blank=True, null=True)),
                ('manufacturer_error', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
