from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class SurfaceReinforcementLocationType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_LOCATION_TYPE_UNKNOWN: _ClassVar[SurfaceReinforcementLocationType]
    SURFACE_REINFORCEMENT_LOCATION_TYPE_FREE_CIRCULAR: _ClassVar[SurfaceReinforcementLocationType]
    SURFACE_REINFORCEMENT_LOCATION_TYPE_FREE_POLYGON: _ClassVar[SurfaceReinforcementLocationType]
    SURFACE_REINFORCEMENT_LOCATION_TYPE_FREE_RECTANGULAR: _ClassVar[SurfaceReinforcementLocationType]
    SURFACE_REINFORCEMENT_LOCATION_TYPE_ON_SURFACE: _ClassVar[SurfaceReinforcementLocationType]

class SurfaceReinforcementReinforcementType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_REINFORCEMENT_TYPE_MESH: _ClassVar[SurfaceReinforcementReinforcementType]
    SURFACE_REINFORCEMENT_REINFORCEMENT_TYPE_REBAR: _ClassVar[SurfaceReinforcementReinforcementType]
    SURFACE_REINFORCEMENT_REINFORCEMENT_TYPE_STIRRUPS: _ClassVar[SurfaceReinforcementReinforcementType]

class SurfaceReinforcementMeshProductRange(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_UNKNOWN: _ClassVar[SurfaceReinforcementMeshProductRange]
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_AUSTRIA_2002_01_01: _ClassVar[SurfaceReinforcementMeshProductRange]
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_CZECH_REPUBLIC: _ClassVar[SurfaceReinforcementMeshProductRange]
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_FRANCE: _ClassVar[SurfaceReinforcementMeshProductRange]
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_GERMANY_1997_01_01: _ClassVar[SurfaceReinforcementMeshProductRange]
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_GERMANY_2001_10_01: _ClassVar[SurfaceReinforcementMeshProductRange]
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_GERMANY_2008_01_01: _ClassVar[SurfaceReinforcementMeshProductRange]
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_NETHERLANDS: _ClassVar[SurfaceReinforcementMeshProductRange]
    SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_UNITED_STATES: _ClassVar[SurfaceReinforcementMeshProductRange]

class SurfaceReinforcementMeshShape(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_MESH_SHAPE_UNKNOWN: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_AQS_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_AQ_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_AS_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_A_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_B_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_CQS_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_CS_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_E_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_G_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_KA_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_KD_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_KH_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_KY_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_K_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_L_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_PAF: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_P_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_Q_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_ROLLS: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_R_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_SHEETS: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_ST: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_W_MESH: _ClassVar[SurfaceReinforcementMeshShape]
    SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_Z_MESH: _ClassVar[SurfaceReinforcementMeshShape]

class SurfaceReinforcementReinforcementDirectionType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_REINFORCEMENT_DIRECTION_TYPE_IN_DESIGN_REINFORCEMENT_DIRECTION: _ClassVar[SurfaceReinforcementReinforcementDirectionType]
    SURFACE_REINFORCEMENT_REINFORCEMENT_DIRECTION_TYPE_PARALLEL_TO_TWO_POINTS: _ClassVar[SurfaceReinforcementReinforcementDirectionType]

class SurfaceReinforcementDesignReinforcementDirection(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_DESIGN_REINFORCEMENT_DIRECTION_A_S_1: _ClassVar[SurfaceReinforcementDesignReinforcementDirection]
    SURFACE_REINFORCEMENT_DESIGN_REINFORCEMENT_DIRECTION_A_S_2: _ClassVar[SurfaceReinforcementDesignReinforcementDirection]

class SurfaceReinforcementProjectionPlane(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_PROJECTION_PLANE_XY_OR_UV: _ClassVar[SurfaceReinforcementProjectionPlane]
    SURFACE_REINFORCEMENT_PROJECTION_PLANE_XZ_OR_UW: _ClassVar[SurfaceReinforcementProjectionPlane]
    SURFACE_REINFORCEMENT_PROJECTION_PLANE_YZ_OR_VW: _ClassVar[SurfaceReinforcementProjectionPlane]

class SurfaceReinforcementLocationRectangleType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_LOCATION_RECTANGLE_TYPE_CORNER_POINTS: _ClassVar[SurfaceReinforcementLocationRectangleType]
    SURFACE_REINFORCEMENT_LOCATION_RECTANGLE_TYPE_CENTER_AND_SIDES: _ClassVar[SurfaceReinforcementLocationRectangleType]

class SurfaceReinforcementStirrupSizeCalculated(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_UNKNOWN: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_1: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_10: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_11: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_12: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_14: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_16: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_18: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_1p5: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_2: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_2p5: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_3: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_4: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_5: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_6: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_7: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_8: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_9: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_10: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_15: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_20: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_25: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_30: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_35: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_45: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_55: _ClassVar[SurfaceReinforcementStirrupSizeCalculated]

class SurfaceReinforcementStirrupSizeAutoMinimum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_AUTO_MINIMUM_UNKNOWN: _ClassVar[SurfaceReinforcementStirrupSizeAutoMinimum]

class SurfaceReinforcementStirrupSizeAutoMaximum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_STIRRUP_SIZE_AUTO_MAXIMUM_UNKNOWN: _ClassVar[SurfaceReinforcementStirrupSizeAutoMaximum]

class SurfaceReinforcementRebarSizeCalculated(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_UNKNOWN: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_1: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_10: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_11: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_12: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_14: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_16: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_18: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_1p5: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_2: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_2p5: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_3: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_4: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_5: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_6: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_7: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_8: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_9: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_10: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_15: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_20: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_25: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_30: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_35: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_45: _ClassVar[SurfaceReinforcementRebarSizeCalculated]
    SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_55: _ClassVar[SurfaceReinforcementRebarSizeCalculated]

class SurfaceReinforcementRebarSizeAutoMinimum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_REBAR_SIZE_AUTO_MINIMUM_UNKNOWN: _ClassVar[SurfaceReinforcementRebarSizeAutoMinimum]

class SurfaceReinforcementRebarSizeAutoMaximum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_REBAR_SIZE_AUTO_MAXIMUM_UNKNOWN: _ClassVar[SurfaceReinforcementRebarSizeAutoMaximum]

class SurfaceReinforcementAdditionalRebarSizeCalculated(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_UNKNOWN: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_1: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_10: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_11: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_12: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_14: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_16: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_18: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_1p5: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_2: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_2p5: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_3: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_4: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_5: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_6: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_7: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_8: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_9: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_10: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_15: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_20: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_25: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_30: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_35: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_45: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_55: _ClassVar[SurfaceReinforcementAdditionalRebarSizeCalculated]

class SurfaceReinforcementAdditionalRebarSizeAutoMinimum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_AUTO_MINIMUM_UNKNOWN: _ClassVar[SurfaceReinforcementAdditionalRebarSizeAutoMinimum]

class SurfaceReinforcementAdditionalRebarSizeAutoMaximum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_AUTO_MAXIMUM_UNKNOWN: _ClassVar[SurfaceReinforcementAdditionalRebarSizeAutoMaximum]
SURFACE_REINFORCEMENT_LOCATION_TYPE_UNKNOWN: SurfaceReinforcementLocationType
SURFACE_REINFORCEMENT_LOCATION_TYPE_FREE_CIRCULAR: SurfaceReinforcementLocationType
SURFACE_REINFORCEMENT_LOCATION_TYPE_FREE_POLYGON: SurfaceReinforcementLocationType
SURFACE_REINFORCEMENT_LOCATION_TYPE_FREE_RECTANGULAR: SurfaceReinforcementLocationType
SURFACE_REINFORCEMENT_LOCATION_TYPE_ON_SURFACE: SurfaceReinforcementLocationType
SURFACE_REINFORCEMENT_REINFORCEMENT_TYPE_MESH: SurfaceReinforcementReinforcementType
SURFACE_REINFORCEMENT_REINFORCEMENT_TYPE_REBAR: SurfaceReinforcementReinforcementType
SURFACE_REINFORCEMENT_REINFORCEMENT_TYPE_STIRRUPS: SurfaceReinforcementReinforcementType
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_UNKNOWN: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_AUSTRIA_2002_01_01: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_CZECH_REPUBLIC: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_FRANCE: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_GERMANY_1997_01_01: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_GERMANY_2001_10_01: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_GERMANY_2008_01_01: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_NETHERLANDS: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_PRODUCT_RANGE_MESHSTANDARD_UNITED_STATES: SurfaceReinforcementMeshProductRange
SURFACE_REINFORCEMENT_MESH_SHAPE_UNKNOWN: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_AQS_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_AQ_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_AS_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_A_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_B_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_CQS_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_CS_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_E_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_G_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_KA_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_KD_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_KH_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_KY_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_K_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_L_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_PAF: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_P_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_Q_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_ROLLS: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_R_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_SHEETS: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_ST: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_W_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_MESH_SHAPE_MESHSHAPE_Z_MESH: SurfaceReinforcementMeshShape
SURFACE_REINFORCEMENT_REINFORCEMENT_DIRECTION_TYPE_IN_DESIGN_REINFORCEMENT_DIRECTION: SurfaceReinforcementReinforcementDirectionType
SURFACE_REINFORCEMENT_REINFORCEMENT_DIRECTION_TYPE_PARALLEL_TO_TWO_POINTS: SurfaceReinforcementReinforcementDirectionType
SURFACE_REINFORCEMENT_DESIGN_REINFORCEMENT_DIRECTION_A_S_1: SurfaceReinforcementDesignReinforcementDirection
SURFACE_REINFORCEMENT_DESIGN_REINFORCEMENT_DIRECTION_A_S_2: SurfaceReinforcementDesignReinforcementDirection
SURFACE_REINFORCEMENT_PROJECTION_PLANE_XY_OR_UV: SurfaceReinforcementProjectionPlane
SURFACE_REINFORCEMENT_PROJECTION_PLANE_XZ_OR_UW: SurfaceReinforcementProjectionPlane
SURFACE_REINFORCEMENT_PROJECTION_PLANE_YZ_OR_VW: SurfaceReinforcementProjectionPlane
SURFACE_REINFORCEMENT_LOCATION_RECTANGLE_TYPE_CORNER_POINTS: SurfaceReinforcementLocationRectangleType
SURFACE_REINFORCEMENT_LOCATION_RECTANGLE_TYPE_CENTER_AND_SIDES: SurfaceReinforcementLocationRectangleType
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_UNKNOWN: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_1: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_10: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_11: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_12: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_14: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_16: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_18: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_1p5: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_2: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_2p5: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_3: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_4: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_5: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_6: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_7: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_8: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_ACI_9: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_10: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_15: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_20: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_25: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_30: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_35: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_45: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_CALCULATED_CSA_55: SurfaceReinforcementStirrupSizeCalculated
SURFACE_REINFORCEMENT_STIRRUP_SIZE_AUTO_MINIMUM_UNKNOWN: SurfaceReinforcementStirrupSizeAutoMinimum
SURFACE_REINFORCEMENT_STIRRUP_SIZE_AUTO_MAXIMUM_UNKNOWN: SurfaceReinforcementStirrupSizeAutoMaximum
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_UNKNOWN: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_1: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_10: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_11: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_12: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_14: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_16: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_18: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_1p5: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_2: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_2p5: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_3: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_4: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_5: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_6: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_7: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_8: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_ACI_9: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_10: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_15: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_20: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_25: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_30: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_35: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_45: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_CALCULATED_CSA_55: SurfaceReinforcementRebarSizeCalculated
SURFACE_REINFORCEMENT_REBAR_SIZE_AUTO_MINIMUM_UNKNOWN: SurfaceReinforcementRebarSizeAutoMinimum
SURFACE_REINFORCEMENT_REBAR_SIZE_AUTO_MAXIMUM_UNKNOWN: SurfaceReinforcementRebarSizeAutoMaximum
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_UNKNOWN: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_1: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_10: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_11: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_12: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_14: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_16: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_18: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_1p5: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_2: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_2p5: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_3: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_4: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_5: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_6: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_7: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_8: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_ACI_9: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_10: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_15: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_20: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_25: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_30: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_35: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_45: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_CALCULATED_CSA_55: SurfaceReinforcementAdditionalRebarSizeCalculated
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_AUTO_MINIMUM_UNKNOWN: SurfaceReinforcementAdditionalRebarSizeAutoMinimum
SURFACE_REINFORCEMENT_ADDITIONAL_REBAR_SIZE_AUTO_MAXIMUM_UNKNOWN: SurfaceReinforcementAdditionalRebarSizeAutoMaximum

class SurfaceReinforcement(_message.Message):
    __slots__ = ("no", "location_type", "user_defined_name_enabled", "name", "surfaces", "material", "reinforcement_type", "rebar_diameter", "rebar_diameter_auto_enabled", "rebar_diameter_auto_minimum", "rebar_diameter_auto_maximum", "rebar_diameter_auto_diameters_enabled", "rebar_diameter_auto_diameters", "rebar_diameter_auto_priority", "rebar_diameter_calculated", "rebar_size", "rebar_spacing", "rebar_spacing_auto_enabled", "rebar_spacing_auto_minimum", "rebar_spacing_auto_maximum", "rebar_spacing_auto_increment", "rebar_spacing_auto_priority", "rebar_spacing_calculated", "stirrup_diameter", "stirrup_diameter_auto_enabled", "stirrup_diameter_auto_minimum", "stirrup_diameter_auto_maximum", "stirrup_diameter_auto_diameters_enabled", "stirrup_diameter_auto_diameters", "stirrup_diameter_auto_priority", "stirrup_diameter_calculated", "stirrup_size", "stirrup_spacing", "stirrup_spacing_auto_enabled", "stirrup_spacing_auto_minimum", "stirrup_spacing_auto_maximum", "stirrup_spacing_auto_increment", "stirrup_spacing_auto_priority", "stirrup_spacing_calculated", "mesh_product_range", "mesh_shape", "mesh_name", "additional_transverse_reinforcement_enabled", "additional_rebar_diameter", "additional_rebar_diameter_auto_enabled", "additional_rebar_diameter_auto_minimum", "additional_rebar_diameter_auto_maximum", "additional_rebar_diameter_auto_diameters_enabled", "additional_rebar_diameter_auto_diameters", "additional_rebar_diameter_auto_priority", "additional_rebar_diameter_calculated", "additional_rebar_size", "additional_rebar_spacing", "additional_rebar_spacing_auto_enabled", "additional_rebar_spacing_auto_minimum", "additional_rebar_spacing_auto_maximum", "additional_rebar_spacing_auto_increment", "additional_rebar_spacing_auto_priority", "additional_rebar_spacing_calculated", "alignment_top_enabled", "alignment_bottom_enabled", "additional_offset_to_concrete_cover_top", "additional_offset_to_concrete_cover_bottom", "reinforcement_direction_type", "design_reinforcement_direction", "first_direction_point_1", "first_direction_point_2", "second_direction_point_1", "second_direction_point_2", "projection_coordinate_system", "projection_plane", "reinforcement_area_as1", "reinforcement_area_as2", "reinforcement_area_as1_top", "reinforcement_area_as2_top", "reinforcement_area_as1_bottom", "reinforcement_area_as2_bottom", "reinforcement_area_as_i", "reinforcement_area_as_i_plus_90", "reinforcement_area_as_i_top", "reinforcement_area_as_i_bottom", "reinforcement_area_as_i_plus_90_top", "reinforcement_area_as_i_plus_90_bottom", "stirrup_reinforcement_area_asw", "acting_region_from", "acting_region_to", "location_rectangle_type", "location_first_x", "location_first_y", "location_second_x", "location_second_y", "location_center_x", "location_center_y", "location_center_side_a", "location_center_side_b", "location_rotation", "location_radius", "polygon_points", "comment", "is_generated", "generating_object_info", "stirrup_size_calculated", "stirrup_size_auto_minimum", "stirrup_size_auto_maximum", "rebar_size_calculated", "rebar_size_auto_minimum", "rebar_size_auto_maximum", "additional_rebar_size_calculated", "additional_rebar_size_auto_minimum", "additional_rebar_size_auto_maximum", "id_for_export_import", "metadata_for_export_import")
    NO_FIELD_NUMBER: _ClassVar[int]
    LOCATION_TYPE_FIELD_NUMBER: _ClassVar[int]
    USER_DEFINED_NAME_ENABLED_FIELD_NUMBER: _ClassVar[int]
    NAME_FIELD_NUMBER: _ClassVar[int]
    SURFACES_FIELD_NUMBER: _ClassVar[int]
    MATERIAL_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_TYPE_FIELD_NUMBER: _ClassVar[int]
    REBAR_DIAMETER_FIELD_NUMBER: _ClassVar[int]
    REBAR_DIAMETER_AUTO_ENABLED_FIELD_NUMBER: _ClassVar[int]
    REBAR_DIAMETER_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    REBAR_DIAMETER_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    REBAR_DIAMETER_AUTO_DIAMETERS_ENABLED_FIELD_NUMBER: _ClassVar[int]
    REBAR_DIAMETER_AUTO_DIAMETERS_FIELD_NUMBER: _ClassVar[int]
    REBAR_DIAMETER_AUTO_PRIORITY_FIELD_NUMBER: _ClassVar[int]
    REBAR_DIAMETER_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    REBAR_SIZE_FIELD_NUMBER: _ClassVar[int]
    REBAR_SPACING_FIELD_NUMBER: _ClassVar[int]
    REBAR_SPACING_AUTO_ENABLED_FIELD_NUMBER: _ClassVar[int]
    REBAR_SPACING_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    REBAR_SPACING_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    REBAR_SPACING_AUTO_INCREMENT_FIELD_NUMBER: _ClassVar[int]
    REBAR_SPACING_AUTO_PRIORITY_FIELD_NUMBER: _ClassVar[int]
    REBAR_SPACING_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_DIAMETER_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_DIAMETER_AUTO_ENABLED_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_DIAMETER_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_DIAMETER_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_DIAMETER_AUTO_DIAMETERS_ENABLED_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_DIAMETER_AUTO_DIAMETERS_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_DIAMETER_AUTO_PRIORITY_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_DIAMETER_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SIZE_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SPACING_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SPACING_AUTO_ENABLED_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SPACING_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SPACING_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SPACING_AUTO_INCREMENT_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SPACING_AUTO_PRIORITY_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SPACING_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    MESH_PRODUCT_RANGE_FIELD_NUMBER: _ClassVar[int]
    MESH_SHAPE_FIELD_NUMBER: _ClassVar[int]
    MESH_NAME_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_TRANSVERSE_REINFORCEMENT_ENABLED_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_DIAMETER_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_DIAMETER_AUTO_ENABLED_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_DIAMETER_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_DIAMETER_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_DIAMETER_AUTO_DIAMETERS_ENABLED_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_DIAMETER_AUTO_DIAMETERS_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_DIAMETER_AUTO_PRIORITY_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_DIAMETER_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SIZE_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SPACING_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SPACING_AUTO_ENABLED_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SPACING_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SPACING_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SPACING_AUTO_INCREMENT_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SPACING_AUTO_PRIORITY_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SPACING_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    ALIGNMENT_TOP_ENABLED_FIELD_NUMBER: _ClassVar[int]
    ALIGNMENT_BOTTOM_ENABLED_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_OFFSET_TO_CONCRETE_COVER_TOP_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_OFFSET_TO_CONCRETE_COVER_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_DIRECTION_TYPE_FIELD_NUMBER: _ClassVar[int]
    DESIGN_REINFORCEMENT_DIRECTION_FIELD_NUMBER: _ClassVar[int]
    FIRST_DIRECTION_POINT_1_FIELD_NUMBER: _ClassVar[int]
    FIRST_DIRECTION_POINT_2_FIELD_NUMBER: _ClassVar[int]
    SECOND_DIRECTION_POINT_1_FIELD_NUMBER: _ClassVar[int]
    SECOND_DIRECTION_POINT_2_FIELD_NUMBER: _ClassVar[int]
    PROJECTION_COORDINATE_SYSTEM_FIELD_NUMBER: _ClassVar[int]
    PROJECTION_PLANE_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS1_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS2_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS1_TOP_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS2_TOP_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS1_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS2_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS_I_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS_I_PLUS_90_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS_I_TOP_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS_I_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS_I_PLUS_90_TOP_FIELD_NUMBER: _ClassVar[int]
    REINFORCEMENT_AREA_AS_I_PLUS_90_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_REINFORCEMENT_AREA_ASW_FIELD_NUMBER: _ClassVar[int]
    ACTING_REGION_FROM_FIELD_NUMBER: _ClassVar[int]
    ACTING_REGION_TO_FIELD_NUMBER: _ClassVar[int]
    LOCATION_RECTANGLE_TYPE_FIELD_NUMBER: _ClassVar[int]
    LOCATION_FIRST_X_FIELD_NUMBER: _ClassVar[int]
    LOCATION_FIRST_Y_FIELD_NUMBER: _ClassVar[int]
    LOCATION_SECOND_X_FIELD_NUMBER: _ClassVar[int]
    LOCATION_SECOND_Y_FIELD_NUMBER: _ClassVar[int]
    LOCATION_CENTER_X_FIELD_NUMBER: _ClassVar[int]
    LOCATION_CENTER_Y_FIELD_NUMBER: _ClassVar[int]
    LOCATION_CENTER_SIDE_A_FIELD_NUMBER: _ClassVar[int]
    LOCATION_CENTER_SIDE_B_FIELD_NUMBER: _ClassVar[int]
    LOCATION_ROTATION_FIELD_NUMBER: _ClassVar[int]
    LOCATION_RADIUS_FIELD_NUMBER: _ClassVar[int]
    POLYGON_POINTS_FIELD_NUMBER: _ClassVar[int]
    COMMENT_FIELD_NUMBER: _ClassVar[int]
    IS_GENERATED_FIELD_NUMBER: _ClassVar[int]
    GENERATING_OBJECT_INFO_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SIZE_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SIZE_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    STIRRUP_SIZE_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    REBAR_SIZE_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    REBAR_SIZE_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    REBAR_SIZE_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SIZE_CALCULATED_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SIZE_AUTO_MINIMUM_FIELD_NUMBER: _ClassVar[int]
    ADDITIONAL_REBAR_SIZE_AUTO_MAXIMUM_FIELD_NUMBER: _ClassVar[int]
    ID_FOR_EXPORT_IMPORT_FIELD_NUMBER: _ClassVar[int]
    METADATA_FOR_EXPORT_IMPORT_FIELD_NUMBER: _ClassVar[int]
    no: int
    location_type: SurfaceReinforcementLocationType
    user_defined_name_enabled: bool
    name: str
    surfaces: _containers.RepeatedScalarFieldContainer[int]
    material: int
    reinforcement_type: SurfaceReinforcementReinforcementType
    rebar_diameter: float
    rebar_diameter_auto_enabled: bool
    rebar_diameter_auto_minimum: float
    rebar_diameter_auto_maximum: float
    rebar_diameter_auto_diameters_enabled: bool
    rebar_diameter_auto_diameters: _containers.RepeatedScalarFieldContainer[int]
    rebar_diameter_auto_priority: int
    rebar_diameter_calculated: float
    rebar_size: float
    rebar_spacing: float
    rebar_spacing_auto_enabled: bool
    rebar_spacing_auto_minimum: float
    rebar_spacing_auto_maximum: float
    rebar_spacing_auto_increment: float
    rebar_spacing_auto_priority: int
    rebar_spacing_calculated: float
    stirrup_diameter: float
    stirrup_diameter_auto_enabled: bool
    stirrup_diameter_auto_minimum: float
    stirrup_diameter_auto_maximum: float
    stirrup_diameter_auto_diameters_enabled: bool
    stirrup_diameter_auto_diameters: _containers.RepeatedScalarFieldContainer[int]
    stirrup_diameter_auto_priority: int
    stirrup_diameter_calculated: float
    stirrup_size: float
    stirrup_spacing: float
    stirrup_spacing_auto_enabled: bool
    stirrup_spacing_auto_minimum: float
    stirrup_spacing_auto_maximum: float
    stirrup_spacing_auto_increment: float
    stirrup_spacing_auto_priority: int
    stirrup_spacing_calculated: float
    mesh_product_range: SurfaceReinforcementMeshProductRange
    mesh_shape: SurfaceReinforcementMeshShape
    mesh_name: str
    additional_transverse_reinforcement_enabled: bool
    additional_rebar_diameter: float
    additional_rebar_diameter_auto_enabled: bool
    additional_rebar_diameter_auto_minimum: float
    additional_rebar_diameter_auto_maximum: float
    additional_rebar_diameter_auto_diameters_enabled: bool
    additional_rebar_diameter_auto_diameters: _containers.RepeatedScalarFieldContainer[int]
    additional_rebar_diameter_auto_priority: int
    additional_rebar_diameter_calculated: float
    additional_rebar_size: float
    additional_rebar_spacing: float
    additional_rebar_spacing_auto_enabled: bool
    additional_rebar_spacing_auto_minimum: float
    additional_rebar_spacing_auto_maximum: float
    additional_rebar_spacing_auto_increment: float
    additional_rebar_spacing_auto_priority: int
    additional_rebar_spacing_calculated: float
    alignment_top_enabled: bool
    alignment_bottom_enabled: bool
    additional_offset_to_concrete_cover_top: float
    additional_offset_to_concrete_cover_bottom: float
    reinforcement_direction_type: SurfaceReinforcementReinforcementDirectionType
    design_reinforcement_direction: SurfaceReinforcementDesignReinforcementDirection
    first_direction_point_1: float
    first_direction_point_2: float
    second_direction_point_1: float
    second_direction_point_2: float
    projection_coordinate_system: int
    projection_plane: SurfaceReinforcementProjectionPlane
    reinforcement_area_as1: float
    reinforcement_area_as2: float
    reinforcement_area_as1_top: float
    reinforcement_area_as2_top: float
    reinforcement_area_as1_bottom: float
    reinforcement_area_as2_bottom: float
    reinforcement_area_as_i: float
    reinforcement_area_as_i_plus_90: float
    reinforcement_area_as_i_top: float
    reinforcement_area_as_i_bottom: float
    reinforcement_area_as_i_plus_90_top: float
    reinforcement_area_as_i_plus_90_bottom: float
    stirrup_reinforcement_area_asw: float
    acting_region_from: float
    acting_region_to: float
    location_rectangle_type: SurfaceReinforcementLocationRectangleType
    location_first_x: float
    location_first_y: float
    location_second_x: float
    location_second_y: float
    location_center_x: float
    location_center_y: float
    location_center_side_a: float
    location_center_side_b: float
    location_rotation: float
    location_radius: float
    polygon_points: SurfaceReinforcementPolygonPointsTable
    comment: str
    is_generated: bool
    generating_object_info: str
    stirrup_size_calculated: SurfaceReinforcementStirrupSizeCalculated
    stirrup_size_auto_minimum: SurfaceReinforcementStirrupSizeAutoMinimum
    stirrup_size_auto_maximum: SurfaceReinforcementStirrupSizeAutoMaximum
    rebar_size_calculated: SurfaceReinforcementRebarSizeCalculated
    rebar_size_auto_minimum: SurfaceReinforcementRebarSizeAutoMinimum
    rebar_size_auto_maximum: SurfaceReinforcementRebarSizeAutoMaximum
    additional_rebar_size_calculated: SurfaceReinforcementAdditionalRebarSizeCalculated
    additional_rebar_size_auto_minimum: SurfaceReinforcementAdditionalRebarSizeAutoMinimum
    additional_rebar_size_auto_maximum: SurfaceReinforcementAdditionalRebarSizeAutoMaximum
    id_for_export_import: str
    metadata_for_export_import: str
    def __init__(self, no: _Optional[int] = ..., location_type: _Optional[_Union[SurfaceReinforcementLocationType, str]] = ..., user_defined_name_enabled: bool = ..., name: _Optional[str] = ..., surfaces: _Optional[_Iterable[int]] = ..., material: _Optional[int] = ..., reinforcement_type: _Optional[_Union[SurfaceReinforcementReinforcementType, str]] = ..., rebar_diameter: _Optional[float] = ..., rebar_diameter_auto_enabled: bool = ..., rebar_diameter_auto_minimum: _Optional[float] = ..., rebar_diameter_auto_maximum: _Optional[float] = ..., rebar_diameter_auto_diameters_enabled: bool = ..., rebar_diameter_auto_diameters: _Optional[_Iterable[int]] = ..., rebar_diameter_auto_priority: _Optional[int] = ..., rebar_diameter_calculated: _Optional[float] = ..., rebar_size: _Optional[float] = ..., rebar_spacing: _Optional[float] = ..., rebar_spacing_auto_enabled: bool = ..., rebar_spacing_auto_minimum: _Optional[float] = ..., rebar_spacing_auto_maximum: _Optional[float] = ..., rebar_spacing_auto_increment: _Optional[float] = ..., rebar_spacing_auto_priority: _Optional[int] = ..., rebar_spacing_calculated: _Optional[float] = ..., stirrup_diameter: _Optional[float] = ..., stirrup_diameter_auto_enabled: bool = ..., stirrup_diameter_auto_minimum: _Optional[float] = ..., stirrup_diameter_auto_maximum: _Optional[float] = ..., stirrup_diameter_auto_diameters_enabled: bool = ..., stirrup_diameter_auto_diameters: _Optional[_Iterable[int]] = ..., stirrup_diameter_auto_priority: _Optional[int] = ..., stirrup_diameter_calculated: _Optional[float] = ..., stirrup_size: _Optional[float] = ..., stirrup_spacing: _Optional[float] = ..., stirrup_spacing_auto_enabled: bool = ..., stirrup_spacing_auto_minimum: _Optional[float] = ..., stirrup_spacing_auto_maximum: _Optional[float] = ..., stirrup_spacing_auto_increment: _Optional[float] = ..., stirrup_spacing_auto_priority: _Optional[int] = ..., stirrup_spacing_calculated: _Optional[float] = ..., mesh_product_range: _Optional[_Union[SurfaceReinforcementMeshProductRange, str]] = ..., mesh_shape: _Optional[_Union[SurfaceReinforcementMeshShape, str]] = ..., mesh_name: _Optional[str] = ..., additional_transverse_reinforcement_enabled: bool = ..., additional_rebar_diameter: _Optional[float] = ..., additional_rebar_diameter_auto_enabled: bool = ..., additional_rebar_diameter_auto_minimum: _Optional[float] = ..., additional_rebar_diameter_auto_maximum: _Optional[float] = ..., additional_rebar_diameter_auto_diameters_enabled: bool = ..., additional_rebar_diameter_auto_diameters: _Optional[_Iterable[int]] = ..., additional_rebar_diameter_auto_priority: _Optional[int] = ..., additional_rebar_diameter_calculated: _Optional[float] = ..., additional_rebar_size: _Optional[float] = ..., additional_rebar_spacing: _Optional[float] = ..., additional_rebar_spacing_auto_enabled: bool = ..., additional_rebar_spacing_auto_minimum: _Optional[float] = ..., additional_rebar_spacing_auto_maximum: _Optional[float] = ..., additional_rebar_spacing_auto_increment: _Optional[float] = ..., additional_rebar_spacing_auto_priority: _Optional[int] = ..., additional_rebar_spacing_calculated: _Optional[float] = ..., alignment_top_enabled: bool = ..., alignment_bottom_enabled: bool = ..., additional_offset_to_concrete_cover_top: _Optional[float] = ..., additional_offset_to_concrete_cover_bottom: _Optional[float] = ..., reinforcement_direction_type: _Optional[_Union[SurfaceReinforcementReinforcementDirectionType, str]] = ..., design_reinforcement_direction: _Optional[_Union[SurfaceReinforcementDesignReinforcementDirection, str]] = ..., first_direction_point_1: _Optional[float] = ..., first_direction_point_2: _Optional[float] = ..., second_direction_point_1: _Optional[float] = ..., second_direction_point_2: _Optional[float] = ..., projection_coordinate_system: _Optional[int] = ..., projection_plane: _Optional[_Union[SurfaceReinforcementProjectionPlane, str]] = ..., reinforcement_area_as1: _Optional[float] = ..., reinforcement_area_as2: _Optional[float] = ..., reinforcement_area_as1_top: _Optional[float] = ..., reinforcement_area_as2_top: _Optional[float] = ..., reinforcement_area_as1_bottom: _Optional[float] = ..., reinforcement_area_as2_bottom: _Optional[float] = ..., reinforcement_area_as_i: _Optional[float] = ..., reinforcement_area_as_i_plus_90: _Optional[float] = ..., reinforcement_area_as_i_top: _Optional[float] = ..., reinforcement_area_as_i_bottom: _Optional[float] = ..., reinforcement_area_as_i_plus_90_top: _Optional[float] = ..., reinforcement_area_as_i_plus_90_bottom: _Optional[float] = ..., stirrup_reinforcement_area_asw: _Optional[float] = ..., acting_region_from: _Optional[float] = ..., acting_region_to: _Optional[float] = ..., location_rectangle_type: _Optional[_Union[SurfaceReinforcementLocationRectangleType, str]] = ..., location_first_x: _Optional[float] = ..., location_first_y: _Optional[float] = ..., location_second_x: _Optional[float] = ..., location_second_y: _Optional[float] = ..., location_center_x: _Optional[float] = ..., location_center_y: _Optional[float] = ..., location_center_side_a: _Optional[float] = ..., location_center_side_b: _Optional[float] = ..., location_rotation: _Optional[float] = ..., location_radius: _Optional[float] = ..., polygon_points: _Optional[_Union[SurfaceReinforcementPolygonPointsTable, _Mapping]] = ..., comment: _Optional[str] = ..., is_generated: bool = ..., generating_object_info: _Optional[str] = ..., stirrup_size_calculated: _Optional[_Union[SurfaceReinforcementStirrupSizeCalculated, str]] = ..., stirrup_size_auto_minimum: _Optional[_Union[SurfaceReinforcementStirrupSizeAutoMinimum, str]] = ..., stirrup_size_auto_maximum: _Optional[_Union[SurfaceReinforcementStirrupSizeAutoMaximum, str]] = ..., rebar_size_calculated: _Optional[_Union[SurfaceReinforcementRebarSizeCalculated, str]] = ..., rebar_size_auto_minimum: _Optional[_Union[SurfaceReinforcementRebarSizeAutoMinimum, str]] = ..., rebar_size_auto_maximum: _Optional[_Union[SurfaceReinforcementRebarSizeAutoMaximum, str]] = ..., additional_rebar_size_calculated: _Optional[_Union[SurfaceReinforcementAdditionalRebarSizeCalculated, str]] = ..., additional_rebar_size_auto_minimum: _Optional[_Union[SurfaceReinforcementAdditionalRebarSizeAutoMinimum, str]] = ..., additional_rebar_size_auto_maximum: _Optional[_Union[SurfaceReinforcementAdditionalRebarSizeAutoMaximum, str]] = ..., id_for_export_import: _Optional[str] = ..., metadata_for_export_import: _Optional[str] = ...) -> None: ...

class SurfaceReinforcementPolygonPointsTable(_message.Message):
    __slots__ = ("rows",)
    ROWS_FIELD_NUMBER: _ClassVar[int]
    rows: _containers.RepeatedCompositeFieldContainer[SurfaceReinforcementPolygonPointsRow]
    def __init__(self, rows: _Optional[_Iterable[_Union[SurfaceReinforcementPolygonPointsRow, _Mapping]]] = ...) -> None: ...

class SurfaceReinforcementPolygonPointsRow(_message.Message):
    __slots__ = ("no", "description", "first_coordinate", "second_coordinate", "comment")
    NO_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    FIRST_COORDINATE_FIELD_NUMBER: _ClassVar[int]
    SECOND_COORDINATE_FIELD_NUMBER: _ClassVar[int]
    COMMENT_FIELD_NUMBER: _ClassVar[int]
    no: int
    description: str
    first_coordinate: float
    second_coordinate: float
    comment: str
    def __init__(self, no: _Optional[int] = ..., description: _Optional[str] = ..., first_coordinate: _Optional[float] = ..., second_coordinate: _Optional[float] = ..., comment: _Optional[str] = ...) -> None: ...
