from colmena.abstractions.channel_abstraction import ChannelInterface
from colmena.abstractions.data_abstraction import DataInterface
from colmena.abstractions.metric_abstraction import MetricInterface